"""HTML report writer.

`detail_fragment` is the single source of truth for the per-domain view: the
static report pages and the browser UI both render it, so the two can never
drift apart.
"""

from __future__ import annotations

import contextlib
import json
import re
import shutil
from collections import Counter
from html import escape
from pathlib import Path

from ..analyze.scoring import UNCHECKED_PREFIX
from ..cache import safe_name
from ..models import (
    AVAILABILITY_LABEL,
    CHECK_LABEL,
    VERDICT_LABEL,
    CheckStatus,
    DomainResult,
    Verdict,
)

DISCLAIMER = (
    "이 검사 결과는 “무위험 보증”이 아닙니다. 클로킹(검색엔진에만 다른 화면을 보여주는 수법)이나 "
    "해킹으로 몰래 심어진 스팸은 저장된 과거 화면만으로는 구조적으로 놓칠 수 있습니다. "
    "돈을 걸기 전에 위에 펼쳐 둔 과거 화면 사진을 눈으로 훑어보세요."
)

LIMITS = [
    "저장된 이력이 없는 것과 열람이 차단된 것은 다릅니다 — 뒤쪽은 이력을 숨겼을 가능성이 있습니다.",
    "백링크 상세는 무료로 받을 수 있는 자료가 없어 근거가 얇습니다(색인 잔존으로 갈음).",
    "상표 검사는 도메인 이름 문자열과 AI 소견 수준의 보조 검사입니다.",
    "OpenRouter 키가 없으면 과거 본문은 AI가 아니라 규칙 검사(기계적 판단)만으로 봅니다 — 문맥을 읽어야 잡히는 것은 놓칠 수 있습니다.",
    "색인 수는 추정치입니다 — 공개 크롤 기록에 남은 주소 수(최대 200)입니다.",
    "구매 가격·경매 시세와 주인이 몇 번 바뀌었는지는 다루지 않습니다.",
]

# 점수 문턱으로 도장을 찍던 수제 감점표는 폐지됐다(2026-08-12). 지금 점수는 순위를
# 매기는 잣대일 뿐이고, 도장은 AI 판정과 기계 거부권이 정한다 — 안내문도 그대로 적는다.
SCORE_GUIDE = "점수는 여러 도메인을 견주는 매입 매력도(0~100)입니다 · 도장 색은 점수가 아니라 판정이 정합니다"

# 어려운 낱말은 제목·라벨에서 곧바로 풀어 준다(따로 용어집을 찾아가지 않게).
INDEX_LABEL = "웹에 남아 있는 페이지(색인)"
REDIRECT_LABEL = "다른 곳으로 넘겨보낸 비율(리다이렉트)"
PARKING_LABEL = "‘도메인 팝니다’ 임시 화면이던 비중(파킹)"

SPAM_VERDICT_LABEL = {
    "spam": "스팸으로 봄(spam)",
    "clean": "깨끗함(clean)",
    "unclear": "판단 유보(unclear)",
    "unknown": "확인 안 됨(unknown)",
}

VERDICT_ORDER = [Verdict.BUY, Verdict.REVIEW, Verdict.NO_HISTORY, Verdict.REJECT]
# DW badge 의 tone 이름. 색은 tokens.css 한 곳에서만 나온다.
VERDICT_TONE = {
    Verdict.BUY: "success",
    Verdict.REVIEW: "warning",
    Verdict.NO_HISTORY: "warning",
    Verdict.REJECT: "error",
}
AVAILABILITY_TONE = {
    "free": "success",
    "soon": "warning",
    "auction": "warning",
    "taken": "neutral",
    "unknown": "neutral",
}

# 도장 색면 — 화면(app-call)과 보고서가 같은 이름을 쓴다. 초록 buy · 노랑 maybe ·
# 빨강 no · 잿빛 hold(남이 쥐고 있어 지금은 못 사는 것).
VERDICT_CALL = {
    Verdict.BUY: "buy",
    Verdict.REVIEW: "maybe",
    Verdict.NO_HISTORY: "maybe",
    Verdict.REJECT: "no",
}

# 판정 근거를 문단이 아니라 짧은 뱃지로 내놓는다. 뜻을 나르는 것은 색과 글자 몇 자다.
# (모델의 참·거짓 칸 → 뱃지 글자) 순서대로 늘어놓으므로 위험이 언제나 앞에 선다.
RULE_TAGS = [
    ("doorway", "검색용 유입 페이지"),
    ("hidden_text", "숨긴 글자"),
    ("link_farm", "링크 무더기"),
    ("autogenerated", "자동 생성 반복"),
    ("language_shift", "쓰던 말이 바뀜"),
]

# ── 스타일시트 — DW 정본 복사본을 합쳐서 만든다 ────────────────────────────
# 값을 이 파일에 베껴 두지 않는다. static/dw/ 아래 원본을 순서대로 읽어 잇고,
# 이 앱만의 레이아웃(static/app.css)을 맨 뒤에 얹는다. 서버는 이것을 /style.css 로
# 내려주고, 보고서 HTML 은 같은 내용을 <style> 로 끼워 넣는다 — zip 을 풀어 파일로
# 열어도 모양이 나와야 하므로.
STATIC_DIR = Path(__file__).resolve().parents[3] / "static"
DW_DIR = STATIC_DIR / "dw"


def _read_css(path: Path) -> str:
    """없거나 못 읽는 파일은 조용히 건너뛴다 — 스타일이 빠져도 앱은 살아 있어야 한다."""
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def build_stylesheet() -> str:
    parts = [
        _read_css(DW_DIR / "tokens.css"),
        _read_css(DW_DIR / "base.css"),
        # '읽는 글'(상세 근거·보고서) 조판. DW 가 주는 정본이라 앱이 다시 만들지 않는다.
        _read_css(DW_DIR / "typography.css"),
    ]
    # 블록(화면 뼈대)은 부품을 짜 맞춘 것이라 부품 뒤에 온다.
    for folder in ("ui", "blocks"):
        one_dir = DW_DIR / folder
        if one_dir.is_dir():
            parts += [_read_css(one) for one in sorted(one_dir.glob("*.css"))]
    parts.append(_read_css(STATIC_DIR / "app.css"))
    joined = "\n".join(part for part in parts if part.strip())
    if not joined:
        return "/* static/dw 를 찾지 못해 스타일 없이 보여 줍니다. */"
    # 이 스타일은 보고서 HTML 한 장 한 장에 통째로 들어간다(파일 하나만 떼어
    # 보내도 모양이 나오게). 그래서 설명 주석과 빈 줄은 빼고 담는다 — 원본
    # static/dw/*.css 는 주석까지 그대로 남아 있다.
    joined = re.sub(r"/\*.*?\*/", "", joined, flags=re.S)
    return re.sub(r"[ \t]*\n[ \t\n]*", "\n", joined).strip()


# 모양 규칙을 앱 켤 때 한 번만 읽어 두면, CSS 를 고쳐도 앱을 껐다 켜기 전에는 화면이 옛 모양
# 그대로다(실제로 새 화면이 안 나온다는 신고가 있었다). 그래서 스타일 파일들이 마지막으로
# 바뀐 시각을 보고, 하나라도 바뀌었으면 그 자리에서 다시 읽는다.
# 처음에는 비워 둔다 — 여기서 미리 한 벌 만들어 봐야 `current_css()` 가 첫 부름에서
# 어차피 다시 만드므로(찍어 둔 시각이 없어 무조건 안 맞는다), 앱 켤 때 DW 스타일 여남은
# 장을 두 번 읽는 셈이었다.
_css_cache: dict[str, object] = {"stamp": None, "text": ""}


def _style_stamp() -> float:
    """모양 규칙에 쓰이는 파일들이 마지막으로 바뀐 시각 중 가장 늦은 것."""
    latest = 0.0
    for one in [STATIC_DIR / "app.css", *DW_DIR.rglob("*.css")]:
        try:
            latest = max(latest, one.stat().st_mtime)
        except OSError:
            continue
    return latest


def current_css() -> str:
    """지금 파일에 적혀 있는 모양 규칙. 안 바뀌었으면 읽어 둔 것을 그대로 돌려준다."""
    stamp = _style_stamp()
    if _css_cache["stamp"] != stamp:
        _css_cache["stamp"] = stamp
        _css_cache["text"] = build_stylesheet()
    return str(_css_cache["text"])

# lucide 아이콘(ISC) 원본 path 를 그대로 인라인한다 — DW 부품이 아이콘 자리를 전제로
# 만들어졌고, 이 앱에는 번들러가 없어 lucide-react 를 못 쓴다.
def _icon(paths: str, size: int = 20, cls: str = "") -> str:
    return (
        f'<svg class="{cls}" xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
        'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" '
        f'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{paths}</svg>'
    )


ICON_WARNING = _icon(
    '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/>'
    '<path d="M12 9v4"/><path d="M12 17h.01"/>',
    cls="dw-alert-icon",
)
ICON_CHEVRON = _icon('<path d="m9 18 6-6-6-6"/>')
ICON_INFO = _icon(
    '<circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>',
    cls="dw-alert-icon",
)
ICON_SUCCESS = _icon(
    '<path d="M21.801 10A10 10 0 1 1 17 3.335"/><path d="m9 11 3 3L22 4"/>',
    cls="dw-alert-icon",
)
# DW alert.jsx 규칙: warning·error 는 급한 소식이라 role="alert", 나머지는 role="status".
# 아이콘도 variant 마다 다르다 — 안내에 경고 삼각형을 그리면 뜻이 뒤집힌다.
ALERT_FACE = {
    "warning": ("alert", ICON_WARNING),
    "error": ("alert", ICON_WARNING),
    "info": ("status", ICON_INFO),
    "success": ("status", ICON_SUCCESS),
}


# 판정 도장 안에 서는 큰 그림 — 색을 못 보는 사람에게는 이 모양이 색을 대신한다.
STAMP_ICON = {
    "buy": _icon(
        '<path d="M21.801 10A10 10 0 1 1 17 3.335"/><path d="m9 11 3 3L22 4"/>',
        size=34,
        cls="app-call-icon",
    ),
    "maybe": _icon(
        '<circle cx="12" cy="12" r="10"/>'
        '<path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><path d="M12 17h.01"/>',
        size=34,
        cls="app-call-icon",
    ),
    "no": _icon(
        '<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>',
        size=34,
        cls="app-call-icon",
    ),
    "hold": _icon(
        '<rect width="18" height="11" x="3" y="11" rx="2" ry="2"/>'
        '<path d="M7 11V7a5 5 0 0 1 10 0v4"/>',
        size=34,
        cls="app-call-icon",
    ),
}

# 뱃지 안에 서는 작은 그림. 위험·주의는 삼각형, 통과는 체크 — 글자를 읽기 전에 갈린다.
TAG_ICON = {
    "error": _icon(
        '<path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/>'
        '<path d="M12 9v4"/><path d="M12 17h.01"/>',
        size=14,
    ),
    "success": _icon('<path d="M20 6 9 17l-5-5"/>', size=14),
}
TAG_ICON["warning"] = TAG_ICON["error"]

ICON_CHEVRON_DOWN = _icon('<path d="m6 9 6 6 6-6"/>')
ICON_IMAGE_OFF = _icon(
    '<line x1="2" x2="22" y1="2" y2="22"/>'
    '<path d="M10.41 10.41a2 2 0 1 1-2.83-2.83"/>'
    '<line x1="13.5" x2="6" y1="13.5" y2="21"/><line x1="18" x2="21" y1="12" y2="15"/>'
    '<path d="M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59"/>'
    '<path d="M21 15V5a2 2 0 0 0-2-2H9"/>',
    size=32,
)


def _alert(text: str, variant: str = "warning") -> str:
    """DW alert — 아이콘 한 칸 + 설명 한 칸."""
    role, icon = ALERT_FACE.get(variant, ALERT_FACE["warning"])
    return (
        f'<div class="dw-alert" data-variant="{variant}" role="{role}">{icon}'
        f'<p class="dw-alert-description">{text}</p></div>'
    )


def _item(
    title: str,
    lines: list[str],
    *,
    href: str | None = None,
    footer: str = "",
    variant: str = "default",
    title_class: str = "",
) -> str:
    """DW list-item 한 줄. 폰 폭(440px)에 표를 우겨넣지 않는다 — 목록 한 줄이 DW 의 답이다."""
    body = (
        '<span class="dw-list-item-content">'
        f'<span class="dw-list-item-title{" " + title_class if title_class else ""}">{title}</span>'
        + "".join(f'<span class="dw-list-item-description">{line}</span>' for line in lines if line)
        + "</span>"
    )
    if href is not None:
        body += f'<span class="dw-list-item-actions">{ICON_CHEVRON}</span>'
    if footer:
        body += f'<span class="dw-list-item-footer">{footer}</span>'
    tag = "a" if href is not None else "div"
    where = f' href="{href}"' if href is not None else ""
    return (
        f'<{tag} class="dw-list-item" data-variant="{variant}" data-size="default"{where}>'
        f"{body}</{tag}>"
    )


def _item_group(items: list[str]) -> str:
    return f'<div class="dw-list-item-group">{"".join(items)}</div>'


# DW·ECC 공통 규칙: 화면에 이모지를 쓰지 않는다. 그런데 이 앱의 글 가운데 일부는
# 우리가 쓴 것이 아니라 AI 가 써 보낸 것이고(한줄평·소견), 예전에 저장해 둔 결과에도
# 옛 문구가 그대로 남아 있다 — 거기 이모지가 섞여 들어오면 화면에 그대로 찍힌다.
# 그래서 글자를 내보내는 길목 한 곳에서 지운다(그림 문자·이모지 변형 표시).
# 화살표(→)는 지우지 않는다 — "정상→위험" 처럼 뜻을 나르는 자리에 쓰고 있다.
_EMOJI = re.compile("[\U0001f000-\U0001faff☀-➿⬀-⯿️⃣]")


def strip_emoji(text: str) -> str:
    """이모지를 지우고 그 자리에 생긴 겹공백을 하나로 줄인다."""
    return re.sub(r"[ \t]{2,}", " ", _EMOJI.sub("", text)).strip()


def _t(value) -> str:
    return escape(strip_emoji(str(value if value is not None else "")))


def _when(stamp: str) -> str:
    """2026-08-05T11:42… → 2026년 8월 5일 11:42. 기계 표기를 사람이 읽는 말로."""
    match = re.match(r"(\d{4})-(\d{2})-(\d{2})T(\d{2}:\d{2})", stamp or "")
    if not match:
        return stamp or "-"
    year, month, day, clock = match.groups()
    return f"{year}년 {int(month)}월 {int(day)}일 {clock}"


def _score_text(result: DomainResult) -> str:
    """점수 = AI가 매긴 매입 매력도(여러 도메인 비교용)."""
    if result.score is None:
        return "점수 없음"
    return f"{result.score:.0f}점" + ("(부분 점수·참고치)" if result.partial_score else "")


def _stamp(result: DomainResult) -> str:
    """판정 도장 — 표·상세 어디서든 같은 모양으로 찍힌다. 채운 배지라 가장 크게 읽힌다."""
    tone = VERDICT_TONE.get(result.verdict, "warning")
    label = result.verdict_label or VERDICT_LABEL[result.verdict]
    return f'<span class="dw-badge" data-tone="{tone}">{_t(label)}</span>'


def _avail(result: DomainResult) -> str:
    """지금 살 수 있나 배지 — 이 도구의 존재 이유라 판정 바로 옆에 둔다.
    도장보다 한 단계 조용하도록 면을 걷어낸 outline(모르는 것은 테두리도 없는 ghost)."""
    key = result.availability if result.availability in AVAILABILITY_LABEL else "unknown"
    label = result.availability_label or AVAILABILITY_LABEL[key]
    tone = AVAILABILITY_TONE.get(key, "neutral")
    variant = "ghost" if key == "unknown" else "outline"
    return f'<span class="dw-badge" data-tone="{tone}" data-variant="{variant}">{_t(label)}</span>'


def _call_of(result: DomainResult) -> str:
    """도장 색면 한 글자. 남이 쥐고 있는 도메인은 '애매한 것'이 아니라 '못 사는 것'이다."""
    if result.verdict is Verdict.REJECT:
        return "no"
    if result.availability == "taken":
        return "hold"
    return VERDICT_CALL.get(result.verdict, "maybe")


def _verdict_stamp(result: DomainResult) -> str:
    """화면 맨 위에 크게 찍히는 판정 도장 — 근거를 읽기 전에 답이 먼저 온다.

    글자는 README 가 정한 네 가지(매입 후보 · 검토 필요 · 이력 없음(신중) · 제외)
    그대로이고, 색면과 그림이 그것을 거들어 스치듯 봐도 갈린다.
    """
    call = _call_of(result)
    label = result.verdict_label or VERDICT_LABEL[result.verdict]
    facts = " · ".join(
        one
        for one in (
            result.availability_label or AVAILABILITY_LABEL["unknown"],
            _score_text(result),
            f"{_when(result.finished_at)} 검사" if result.finished_at else "",
        )
        if one
    )
    return (
        f'<div class="app-call" data-call="{call}">{STAMP_ICON[call]}'
        f'<span class="app-call-mark">{_t(label)}</span>'
        f'<p class="app-call-sub">{_t(facts)}</p></div>'
    )


def _tags(result: DomainResult) -> list[tuple[str, str]]:
    """판정 근거를 (색, 글자 몇 자)로 잘라 낸다 — 긴 문단 대신 늘어놓을 뱃지들.

    순서가 곧 중요도다: 사면 안 되는 흔적 → 조심할 것 → 그냥 사실 → 못 본 검사.
    맨 끝의 '못 본 검사'를 빼먹으면 안 한 검사가 '깨끗함'으로 읽힌다.
    """
    out: list[tuple[str, str]] = []
    if result.blocklist.listed:
        out.append(("error", "공개 위험 명단 등재"))
    if result.spamhaus.listed:
        out.append(("error", "스팸 블랙리스트 등재"))
    if result.safebrowsing.listed:
        out.append(("error", "구글이 위험하다고 표시"))
    if result.wayback.excluded:
        out.append(("error", "과거 이력 열람 차단"))
    out += [("error", label) for field, label in RULE_TAGS if getattr(result.rules, field)]
    if result.ai.spam.verdict == "spam":
        out.append(("error", "AI가 스팸으로 봄"))
    if result.ai.transition_risk:
        out.append(("error", "하던 일이 위험 업종으로 바뀜"))

    if result.ai.trademark_risk:
        out.append(("warning", "남의 상표에 걸릴 수 있음"))
    if result.rules.check.ok and result.rules.parking_ratio >= 0.3:
        out.append(("warning", f"판매용 빈 화면 {result.rules.parking_ratio:.0%}"))
    if result.index.current_parking:
        out.append(("warning", "지금은 판매용 빈 화면"))
    if result.ai.spam.verdict == "unclear":
        out.append(("warning", "AI가 판단을 미룸"))

    if result.wayback.has_history:
        span = f"{result.wayback.first_seen[:4]}~{result.wayback.last_seen[:4]}년"
        out.append(("neutral", f"{span} 운영"))
        out.append(("neutral", f"저장된 화면 {result.wayback.total_captures}장"))
    else:
        out.append(("warning", "저장된 과거 화면 없음"))
    if result.index.check.ok:
        out.append(("neutral", f"지금 웹에 남은 페이지 {result.index.indexed_count}건"))
    if result.ai.spam.verdict == "clean":
        out.append(("success", "AI가 깨끗하다고 봄"))
    if result.verdict is Verdict.BUY:
        out.append(("success", "걸리는 신호 없음"))

    out += [("miss", f"확인 못 함 · {label}") for label in result.unchecked]
    out += [("miss", f"안 돌림 · {label}") for label in result.not_run]
    return out


def _tag(tone: str, text: str) -> str:
    """뱃지 하나. '못 본 검사'만 점선 테두리다 — 채운 뱃지와 나란히 서도 빈칸으로 읽힌다."""
    if tone == "miss":
        return (
            '<span class="dw-badge app-tag-miss" data-tone="neutral" '
            f'data-variant="outline">{_t(text)}</span>'
        )
    return (
        f'<span class="dw-badge" data-tone="{tone}">{TAG_ICON.get(tone, "")}{_t(text)}</span>'
    )


def _tag_row(result: DomainResult) -> str:
    """상세 화면의 근거 뱃지 줄 — 있는 대로 전부 늘어놓는다."""
    tags = _tags(result)
    if not tags:
        return ""
    cells = "".join(f"<li>{_tag(tone, text)}</li>" for tone, text in tags)
    return f'<ul class="app-tags">{cells}</ul>'


def _tag_strip(result: DomainResult, limit: int = 3) -> str:
    """목록 한 줄에 들어가는 짧은 뱃지 몇 개 — 수백 줄을 훑는 자리라 문장을 세우지 않는다.

    담는 것은 판정을 가른 것뿐이라 '그냥 사실'(neutral)과 '못 본 검사'는 뺀다.
    (목록 줄 안이라 `<ul>` 이 아니라 `<span>` 이다 — 설명 칸이 span 이기 때문.)
    """
    tags = [(tone, text) for tone, text in _tags(result) if tone != "miss"]
    tags.sort(key=lambda one: one[0] == "neutral")
    if not tags:
        return ""
    return (
        '<span class="app-tags">'
        + "".join(_tag(tone, text) for tone, text in tags[:limit])
        + "</span>"
    )


def _reason_rows(result: DomainResult) -> list[tuple[str, str, str]]:
    """(색, 앞뱃지, 문장) 줄들. 화면과 목록이 같은 것을 보게 한 곳에서만 만든다.

    '필수 검사 미확인 —' 로 시작하는 것은 그 도메인 얘기가 아니라 이 도구의 사정이라
    맨 뒤로 미루고 뱃지도 '못 봄'으로 달리 단다. 표식은 만드는 자리(scoring)에서 붙인
    것을 그대로 본다 — 문장의 뜻을 낱말로 넘겨짚지 않는다.
    그리고 붙인 표식은 화면에서 떼어 낸다: 뱃지가 이미 같은 말을 하고 있어서
    문장 앞에 한 번 더 적으면 같은 뜻이 두 번 선다.
    """
    rows: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for tone, mark, texts in (
        ("error", "사면 안 됨", result.fatal_reasons),
        ("warning", "조심", result.warn_reasons),
    ):
        for text in texts:
            if text in seen:  # 같은 문장이 두 목록에 다 올라온 적이 있다
                continue
            seen.add(text)
            if text.startswith(UNCHECKED_PREFIX):
                rows.append(("neutral", "못 봄", text[len(UNCHECKED_PREFIX):]))
            else:
                rows.append((tone, mark, text))
    rows.sort(key=lambda row: row[1] == "못 봄")
    if not rows:
        good = result.ai.verdict_reason or result.one_liner
        if good:
            rows = [("success", "통과", good)]
    return rows


def _reason_lines(rows: list[tuple[str, str, str]]) -> str:
    """이유를 한 줄씩. 줄 앞의 뱃지가 어느 쪽 이야기인지 말한다."""
    if not rows:
        return ""
    return (
        '<ol class="app-why">'
        + "".join(
            f'<li><span class="dw-badge" data-tone="{tone}">{_t(mark)}</span>'
            f"<span>{_t(text)}</span></li>"
            for tone, mark, text in rows
        )
        + "</ol>"
    )


def _lead(result: DomainResult, rows: list[tuple[str, str, str]]) -> str:
    """도장 밑 한 문장. 한줄평의 첫 문장만 쓴다.

    한줄평은 뒤로 갈수록 "저장된 화면 2000장", "지금 웹에 남은 페이지 0건" 처럼
    바로 아래 뱃지 줄에 이미 서 있는 사실을 다시 늘어놓는다. 첫 문장이 답이고
    나머지는 되풀이라 여기서는 첫 문장까지만 세운다.
    이유 줄 맨 위와 같은 말이면 아예 세우지 않는다 — 같은 문장이 두 번 선다.
    """
    text = (result.one_liner or "").strip()
    if not text:
        return ""
    head = text.split(". ")[0].rstrip(". ").strip()
    if not head or any(head and head in one[2] for one in rows[:1]):
        return ""
    return f'<p class="app-lead">{_t(head)}.</p>'


def _check_line(check) -> str:
    """검사 한 줄. 안 돌린 검사를 '-' 로 두면 '깨끗함'으로 읽힌다 — 안 했다고 적는다."""
    if check.note:
        return _t(check.note)
    if check.status is CheckStatus.NOT_RUN:
        return "검사하지 않았습니다(키가 없거나 꺼 둠) — 깨끗하다는 뜻이 아닙니다."
    if check.status is CheckStatus.UNCHECKED:
        return "검사했지만 답을 못 받았습니다 — 깨끗하다는 뜻이 아닙니다."
    return "이상 없음."


def _list(items: list[str], empty: str = "없음") -> str:
    if not items:
        return f'<p class="muted">{escape(empty)}</p>'
    return "<ul>" + "".join(f"<li>{_t(i)}</li>" for i in items) + "</ul>"


def _timeline(result: DomainResult) -> str:
    counts = result.wayback.year_counts
    if not counts:
        return '<p class="muted">저장된 이력이 없습니다.</p>'
    top = max(counts.values())
    years = sorted(counts)
    # 규칙 검사가 스팸 흔적을 잡은 해는 막대를 빨갛게 세운다 — 어느 시절이 문제였는지
    # 문장으로 읽지 않고 한눈에 잡히게. 표식이 붙는 해가 없으면 빨간 막대도 없다.
    risk_years = {stamp[:4] for stamp in result.rules.risk_timestamps if stamp}
    bars = "".join(
        f'<div style="height:{max(4, int(counts[y] / top * 56))}px" '
        f'{" data-risk=\"true\"" if y in risk_years else ""} '
        f'title="{_t(y)}년 {counts[y]}건{"  — 스팸 흔적 나옴" if y in risk_years else ""}"></div>'
        for y in years
    )
    # 폰 폭에서는 막대가 20px 아래로 내려간다 — 막대마다 해를 적으면 글자가 서로 겹쳐
    # 읽을 수 없다. 그래서 해는 양 끝에만 적고, 막대 하나하나는 마우스를 올리면 알려 준다.
    scale = (
        f'<p class="app-years-scale muted"><span>{_t(years[0])}년</span>'
        f"<span>{_t(years[-1])}년</span></p>"
    )
    legend = (
        '<p class="muted">빨간 막대 = 스팸 흔적이 나온 해</p>'
        if risk_years & set(years)
        else ""
    )
    gaps = (
        f'<p class="muted">기록이 비어 있는 해: {", ".join(str(g) for g in result.wayback.gap_years)}</p>'
        if result.wayback.gap_years
        else ""
    )
    # 막대와 해 표시는 한 덩어리다 — 따로 두면 글 리듬이 둘 사이를 벌려 놓는다.
    return (
        f'<div class="app-timeline"><div class="app-years">{bars}</div>{scale}</div>'
        f"{legend}{gaps}"
    )


def _figure(shot, capture_base: str) -> str:
    """과거 화면 사진 한 장. 시기 이름표는 사진 위에 얹는다 — 사진과 이름표가
    떨어져 있으면 여러 장을 훑을 때 어느 이름표가 어느 사진인지 흔들린다.

    저장된 화면은 세로로 아주 길다. 통째로 줄여 넣으면 글씨가 개미만 해지므로
    사람이 알아보는 윗부분만 4:3 으로 잘라 보여 준다(자르기는 CSS 가 한다).
    """
    when = shot.timestamp
    day = f"{when[:4]}년 {int(when[4:6])}월" if len(when) >= 6 else when
    # 시기 이름표 뒤에 붙은 해 묶음("(2010~2011)")은 떼어 낸다 — 바로 밑 캡션이
    # 찍은 달을 더 정확히 말하고 있어서, 사진 위 좁은 이름표를 두 줄로 밀 뿐이다.
    label = re.sub(r"\s*\(\d{4}(~\d{4})?\)\s*$", "", shot.label).strip() or shot.label
    return (
        "<figure>"
        f'<span class="app-shot-frame">'
        f"<img src=\"{_t(capture_base.rstrip('/'))}/{_t(Path(shot.file).name)}\" "
        f'alt="{_t(shot.label)} 무렵의 화면" loading="lazy">'
        f'<span class="dw-badge app-shot-when" data-tone="neutral">{_t(label)}</span>'
        "</span>"
        f'<figcaption class="muted">{_t(day)} · '
        f'<a href="{_t(shot.url)}" target="_blank" rel="noopener">웨이백에서 원본 보기</a>'
        "</figcaption></figure>"
    )


def _captures(result: DomainResult, capture_base: str) -> str:
    """저장된 과거 화면 전부. 접지 않는다 — 이 도구가 내놓는 가장 강한 증거다.

    사진이 없으면 조용히 비워 두지 않고 왜 없는지를 빈 자리에 적는다.
    빈 화면은 '깨끗하다'가 아니라 '못 봤다'는 뜻이기 때문이다.
    한 장도 못 찍은 것과 몇 장 놓친 것은 다른 이야기라 자리도 달리 준다.
    """
    items = sorted(result.captures.items, key=lambda shot: shot.timestamp)
    # 사진 찍기가 어떻게 끝났는지 프로그램은 알고 있으면서 화면에는 안 적고 있었다.
    # 몇 장 실패했다는 말이 없으면, 남은 사진 몇 장이 '과거 전부'로 읽힌다.
    note = (result.captures.check.note or "").strip()
    if not items:
        # 왜 없는지는 낱말이 아니라 데이터로 가른다 — 웨이백에 저장된 화면이
        # 아예 없던 것인가, 있는데 사진으로 못 옮긴 것인가.
        if result.wayback.has_history:
            title = "과거 화면 사진을 못 남겼습니다"
            # 여기서 '원본 보기' 링크를 가리키면 안 된다 — 그 링크는 사진 밑에 붙는
            # 것이라, 사진이 한 장도 없는 이 자리에는 아예 없다.
            why = (
                f"웨이백에 저장된 화면이 {result.wayback.total_captures}장 있는데 "
                "사진으로 옮기지 못했습니다 — 사진 없이 나머지 근거로만 판정했습니다."
            )
        else:
            title = "과거 화면 사진이 없습니다"
            why = "웨이백에 저장된 과거 화면 자체가 없어서 찍을 것이 없었습니다."
        detail = f'<p class="dw-empty-state-description muted">{_t(note)}</p>' if note else ""
        return (
            '<div class="dw-empty-state">'
            f'<span class="dw-empty-state-media" data-variant="icon">{ICON_IMAGE_OFF}</span>'
            f'<p class="dw-empty-state-title">{title}</p>'
            f'<p class="dw-empty-state-description">{why}</p>{detail}</div>'
        )
    shots = "".join(_figure(one, capture_base) for one in items)
    tail = f'<p class="muted app-shots-note">사진 찍기 결과 · {_t(note)}</p>' if note else ""
    return f'<div class="app-shots">{shots}</div>{tail}'


def _topic_story(result: DomainResult) -> str:
    """주제 시기별 역사 — 시기 한 줄씩. 사진은 위 '과거 화면' 칸이 통째로 맡는다.

    예전에는 이 목록 안에 사진을 한 장씩 끼워 넣고 아래 캡쳐 칸에서 그것을 빼는
    식이었다. 그래서 사진이 두 곳에 쪼개져 어느 쪽도 크게 서지 못했다.
    """
    periods = result.ai.topic_periods
    if not periods:
        text = result.ai.topic_history or "AI 분석을 하지 않아 주제 역사를 못 읽었습니다."
        return f'<p class="muted">{_t(text)}</p>'
    rows = []
    for period in periods:
        start = str(period.get("start", ""))[:4]
        end = str(period.get("end", ""))[:4]
        span = f"{start}~{end}" if start and end and start != end else (start or end)
        rows.append(
            f'<li><span class="dw-badge" data-tone="accent">{_t(span)}</span>'
            f"<span>{_t(period.get('topic', ''))}</span></li>"
        )
    summary = f"<p>{_t(result.ai.topic_history)}</p>" if result.ai.topic_history else ""
    return f'<ol class="app-why">{"".join(rows)}</ol>{summary}'


def detail_fragment(
    result: DomainResult, capture_base: str = "../captures", *, stamp: bool = True
) -> str:
    """The full evidence view for one domain (no <html> wrapper).

    `stamp=False` 는 앱 화면이 쓴다 — 그 화면은 시트 머리에 제 도장을 이미 찍어 두어서
    여기서 또 찍으면 같은 판정이 한 화면에 두 번 선다.

    이 칸은 **접히지 않는다.** 예전에는 "자세한 근거·못 본 검사 보기"로 접어 두고
    사람에게 다시 확인하라고 링크를 늘어놓았는데, 그러면 검사한 프로그램이 답을 안
    내놓고 일을 떠넘기는 꼴이다(2026-08-23 운영자 지시). 판정 근거·과거 화면 사진은
    처음부터 펼쳐 두고, 접는 것은 '더 보기'의 곁가지뿐이다.
    """
    registration = result.registration
    age = result.wayback.age_years
    # 이유 줄은 한 곳에서만 만든다 — 도장 밑 한 문장(_lead)이 같은 말을 되풀이하는지
    # 견주려면 그 줄들을 먼저 손에 쥐고 있어야 한다.
    reason_rows = _reason_rows(result)
    # 수제 감점표는 폐지 — 판정 근거는 AI 종합 소견 한 줄로 보여 준다.
    ai_opinion = (
        f"<p><b>AI 종합 소견:</b> {_t(result.ai.verdict_reason)}"
        + (
            f' <span class="muted">(매입 매력도 {result.ai.buy_score:.0f}점 — 여러 도메인 비교용)</span>'
            if result.ai.buy_score is not None
            else ""
        )
        + "</p>"
        if result.ai.verdict_reason or result.ai.buy_score is not None
        else '<p class="muted">AI 종합 소견 없음(AI 분석이 돌지 않음)</p>'
    )
    topics = "".join(
        f"<li><b>{_t(t.get('topic'))}</b> — {_t(t.get('reason'))}</li>"
        for t in result.recommended_topics
    )
    # 인용은 민무늬 blockquote — 모양은 DW 프로즈 정본(typography.css)이 낸다.
    # 누가 한 말인지 없으면 화면에 문장 몇 개가 까닭 없이 떠 있게 된다.
    quotes = (
        "<h3>AI가 근거로 든 문장</h3>"
        + "".join(f"<blockquote>{_t(q)}</blockquote>" for q in result.ai.spam.quotes)
        if result.ai.spam.quotes
        else ""
    )
    fallback_note = (
        f'<p class="muted">기본 모델이 실패해 대체 모델 {_t(result.ai.model)}로 분석했습니다 — 단가가 다를 수 있습니다.</p>'
        if result.ai.fallback_used
        else ""
    )
    index_line = (
        f"색인 {result.index.indexed_count}건"
        + (" · " + _t(result.index.check.note) if result.index.check.note else "")
        if result.index.check.ok
        else "못 쟀음 — " + _t(result.index.check.note or "확인하지 못했습니다.")
    )
    spam_verdict = SPAM_VERDICT_LABEL.get(result.ai.spam.verdict, result.ai.spam.verdict)
    # 규칙 검사를 못 했는데 "특별한 흔적 없음"이라고 쓰면 못 한 것이 깨끗함으로 읽힌다.
    rules_evidence = (
        _list(result.rules.evidence, "특별한 흔적 없음")
        if result.rules.check.ok
        else '<p class="muted">'
        + _t(result.rules.check.note or "규칙 검사를 못 했습니다.")
        + " (흔적이 없다는 뜻이 아닙니다)</p>"
    )
    # 첫 화면에 서는 숫자는 넷뿐이다 — 살지 말지를 가르는 것만. 등록일·자료 출처처럼
    # 궁금해서 찾아보는 값은 아래 '더 보기'로 내렸다.
    facts = [
        (
            "운영한 기간",
            f"약 {age:.0f}년" if result.wayback.has_history else "기록 없음",
        ),
        (
            "저장된 화면",
            f"{result.wayback.total_captures}장" if result.wayback.has_history else "0장",
        ),
        (
            "지금 웹에 남은 페이지",
            f"{result.index.indexed_count}건" if result.index.check.ok else "못 쟀음",
        ),
        ("만료일", _t(registration.expires or "알 수 없음")),
    ]
    fact_cards = "".join(
        '<div class="dw-card" data-elevation="float" data-size="sm">'
        f'<p class="dw-card-description">{label}</p>'
        f'<p class="dw-card-title">{value}</p></div>'
        for label, value in facts
    )
    # 도메인 이름은 제목 줄(dw-block-shell-title)이 든다 — 붙어 있어서 굴러도 안 사라진다.
    # 여기서 한 번 더 적으면 한 페이지에 h1 이 둘이 되고 첫 화면을 한 줄 낭비한다.
    return f"""
{_verdict_stamp(result) if stamp else ""}
{_lead(result, reason_rows)}

<h2>이렇게 봤다</h2>
{_tag_row(result)}
{_reason_lines(reason_rows)}

<h2>과거에 이렇게 생겼었다</h2>
{_captures(result, capture_base)}

<h2>얼마나 오래 굴러갔나</h2>
<div class="app-grid">{fact_cards}</div>
{_timeline(result)}

<h2>무엇을 하던 도메인인가</h2>
{_topic_story(result)}
{quotes}
{fallback_note}

<details class="app-more">
<summary>더 보기 — 검사 항목별 원자료{ICON_CHEVRON_DOWN}</summary>

<h3>AI 종합 소견</h3>
{ai_opinion}
<p>스팸성 판정: {_t(spam_verdict)} · 확신도 {result.ai.spam.confidence:.2f}</p>
<p><b>전환 방향:</b> {_t(result.ai.transition or "확인 안 됨")}</p>
<p><b>콘텐츠 품질:</b> {_t(result.ai.content_quality or "확인 안 됨")}</p>
<p><b>상표 소견:</b> {_t(result.ai.trademark or "확인 안 됨")}</p>

<h3>운영방식 규칙이 찾은 흔적</h3>{rules_evidence}

<h3>{INDEX_LABEL}</h3>
<p>{index_line}</p>
{_list(result.index.titles[:10], "색인된 제목 없음")}

<h3>블랙리스트</h3>
<p>공개 위험 명단(UT1): {_check_line(result.blocklist.check)}<br>
스팸하우스: {_check_line(result.spamhaus.check)}<br>
세이프 브라우징: {_check_line(result.safebrowsing.check)}</p>

<h3>등록 정보</h3>
<p>등록일 {_t(registration.created or "알 수 없음")} ·
취득 상태 {_t(result.acquisition)} ·
재등록(드랍) 이력 {"있음" if registration.redropped else "확인 안 됨"} ·
자료 출처 {_t(registration.source or "없음")}</p>

<h3>저장 이력 자세히</h3>
<p>{REDIRECT_LABEL} {result.wayback.redirect_ratio:.0%} ·
{PARKING_LABEL} {result.rules.parking_ratio:.0%}</p>
{f'<p class="muted">확인 범위: {_t(result.wayback.coverage_note)}</p>' if result.wayback.coverage_note else ""}

<h3>사면 이어가기 좋은 주제 (AI 추천)</h3>
{f"<ul>{topics}</ul>" if topics else '<p class="muted">추천 주제 없음</p>'}
</details>
"""


def _page(title: str, bar: str, body: str, action: str = "") -> str:
    """DW 블록 app-shell-mobile 그대로 — 붙어 있는 제목 줄 + 가운데만 구르는 본문.
    보고서에는 화면을 옮길 곳이 없으므로 탭 줄만 없다.

    모양 규칙은 같은 폴더의 style.css 를 가리킨다. 예전에는 페이지마다 통째로
    끼워 넣었는데, 도메인 1,000개면 페이지 1,001장 × 50KB = 약 78MB 가 되어
    메일에 붙지 않았다. 보고서는 언제나 폴더 한 벌로 나가므로 한 장만 두면 된다.
    """
    slot = f'<div class="dw-block-shell-action">{action}</div>' if action else ""
    return (
        '<!doctype html><html lang="ko"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">'
        f'<title>{_t(title)}</title><link rel="stylesheet" href="style.css"></head>'
        '<body><div class="dw-block-shell"><header class="dw-block-shell-bar">'
        f'<h1 class="dw-block-shell-title">{_t(bar)}</h1>{slot}</header>'
        f'<main class="dw-block-shell-body"><div class="dw-prose">{body}</div>'
        "</main></div></body></html>"
    )


def render_detail_page(result: DomainResult, capture_base: str = "../captures") -> str:
    # 면책 문구는 맨 아래로 내렸다. 맨 위는 판정 도장 자리다 — 답을 보러 온 사람에게
    # 첫 화면을 주의 문구로 채우면 정작 볼 것이 한 뼘 아래로 밀린다.
    body = detail_fragment(result, capture_base) + _alert(escape(DISCLAIMER))
    back = (
        '<a class="dw-button" data-variant="ghost" data-size="sm" href="index.html">전체 목록으로</a>'
    )
    return _page(f"{result.domain} 상세 — 낙장도메인 품질 체커", result.domain, body, action=back)


# 지금 살 수 있는 것 → 곧 살 수 있는 것 → 경매 → 모름 → 남이 쓰는 중 순서.
_BUY_RANK = {"free": 0, "soon": 1, "auction": 2, "unknown": 3, "taken": 4}


def _buy_rank(result: DomainResult) -> int:
    return _BUY_RANK.get(result.availability, 3)


def _tally(results: list[DomainResult]) -> str:
    """맨 위 개수 판 — 몇 개가 초록이고 몇 개가 빨강인지 숫자 넷으로 끝낸다.

    수백 줄을 받아 든 사람이 처음 묻는 것은 "몇 개나 살 만한가"다.
    그 답을 목록을 굴려 세게 하지 않는다.
    """
    cells = []
    for verdict in VERDICT_ORDER:
        hit = sum(1 for r in results if r.verdict is verdict)
        if not hit:
            continue
        call = VERDICT_CALL.get(verdict, "maybe")
        cells.append(
            f'<li data-call="{call}"><b>{hit}</b>'
            f"<span>{_t(VERDICT_LABEL[verdict])}</span></li>"
        )
    return f'<ul class="app-tally">{"".join(cells)}</ul>' if cells else ""


def render_index(results: list[DomainResult]) -> str:
    groups = []
    for verdict in VERDICT_ORDER:
        rows = [r for r in results if r.verdict is verdict]
        if not rows:
            continue
        # 점수만으로 줄을 세우면 "매입 후보" 맨 위에 못 사는 도메인이 온다.
        # 이 도구는 살 것을 고르라고 있는 물건이라, 살 수 있는 것을 먼저 올린다.
        rows.sort(key=lambda r: (_buy_rank(r), r.score is None, -(r.score or 0)))
        body = _item_group(
            [
                # 한줄평(문장)은 뺐다 — 수백 줄을 훑는 자리에 문장이 서면 눈이 읽느라
                # 멈춘다. 같은 내용을 판정 뱃지 몇 개로 줄여 세운다(문장은 상세에 있다).
                _item(
                    _t(r.domain),
                    [_tag_strip(r)],
                    href=f"{_t(safe_name(r.domain))}.html",
                    title_class="app-domain",
                    footer=f'<span class="app-badges">{_stamp(r)}{_avail(r)}</span>'
                    f'<span class="app-score">{_t(_score_text(r))}</span>',
                )
                for r in rows
            ]
        )
        groups.append(f"<h2>{_t(VERDICT_LABEL[verdict])} — {len(rows)}개</h2>{body}")

    # 합집합만 적으면 "AI 분석 못 함"이라 써 놓고 옆 표에는 AI 한줄평이 보여 모순으로 읽힌다.
    # 몇 개 도메인에서 못 했는지 함께 적어 준다.
    counts = Counter(label for r in results for label in set(r.unchecked + r.not_run))
    missing = [
        label if hit == len(results) else f"{label} — 도메인 {len(results)}개 중 {hit}개에서"
        for label, hit in sorted(counts.items())
    ]
    # 언제 검사한 결과인지 없으면 묵은 답을 오늘 것으로 읽는다.
    checked_at = max((r.finished_at for r in results if r.finished_at), default="")
    # 개수 판이 먼저다 — 목록을 받아 든 사람이 처음 묻는 "몇 개나 살 만한가"의 답이라
    # 언제 검사했는지보다 앞에 선다. 점수 읽는 법 같은 설명은 첫 화면에서 걷어내
    # 아래 '더 보기' 로 내렸다(2026-08-23 운영자 지시 — 첫 화면이 글자 나열이면 안 읽는다).
    body = (
        _tally(results)
        + f'<p class="muted">{_t(_when(checked_at))}에 검사함 · 도메인 {len(results)}개</p>'
        + "".join(groups)
        + _alert(escape(DISCLAIMER))
        # 목록 화면에서 접는 것은 '이 도구가 원래 못 보는 것' 뿐이다. 도메인 하나하나의
        # 판정 근거는 상세에 전부 펼쳐져 있다.
        + '<details class="app-more"><summary>이 검사가 못 보는 것'
        + ICON_CHEVRON_DOWN
        + "</summary>"
        + f'<h3>점수 읽는 법</h3><p>{escape(SCORE_GUIDE)}</p>'
        + "<h3>이 검사의 한계</h3>"
        + _list(LIMITS)
        + "<h3>이번 실행에서 확인하지 못한 검사</h3>"
        + _list(missing, "없음")
        + '<p class="muted">원자료: <a href="results.json">results.json</a> · '
        + f"검사 항목 이름: {_t(', '.join(CHECK_LABEL.values()))}</p></details>"
    )
    return _page("낙장도메인 품질 체커 결과", "검사 결과", body)


def _copy_fonts(out_dir: Path) -> None:
    """표시용 글꼴을 보고서 폴더에도 한 벌 둔다.

    보고서는 폴더째 메일로 나간다. `style.css` 가 글꼴을 `fonts/…` 로 부르므로,
    글꼴이 옆에 없으면 받는 사람 화면에서는 글씨가 이 글꼴로 나오지 않는다.
    글꼴이 없어도 보고서 자체는 나와야 하니 실패는 조용히 넘긴다.
    """
    src_dir = STATIC_DIR / "fonts"
    if not src_dir.is_dir():
        return
    dest_dir = out_dir / "fonts"
    dest_dir.mkdir(parents=True, exist_ok=True)
    for name in ("Paperlogy-4Regular.woff2", "Paperlogy-7Bold.woff2"):
        one = src_dir / name
        if one.is_file():
            with contextlib.suppress(OSError):
                shutil.copyfile(one, dest_dir / name)


def write_report(results: list[DomainResult], base: Path | str) -> Path:
    """Write data/report/index.html plus one page per domain; returns the index."""
    out_dir = Path(base) / "report"
    out_dir.mkdir(parents=True, exist_ok=True)
    # 모양 규칙 한 장. 페이지마다 통째로 끼워 넣으면 도메인 1,000개에 약 78MB 가 된다.
    (out_dir / "style.css").write_text(current_css(), encoding="utf-8")
    _copy_fonts(out_dir)
    keep = {"index.html"}
    for result in results:
        name = f"{safe_name(result.domain)}.html"
        keep.add(name)
        (out_dir / name).write_text(render_detail_page(result), encoding="utf-8")
    # 지난 실행에서 남은 도메인 페이지는 지운다 — 목록에 없는데 파일만 남으면
    # 옛 결과를 오늘 것으로 착각한다.
    for stale in out_dir.glob("*.html"):
        if stale.name not in keep:
            with contextlib.suppress(OSError):
                stale.unlink()
    index = out_dir / "index.html"
    index.write_text(render_index(results), encoding="utf-8")
    (out_dir / "results.json").write_text(
        json.dumps([r.model_dump(mode="json") for r in results], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return index
