"""적대 심사(품질 심사관·진상 고객)에서 나온 결함의 회귀 시험.

여기 있는 시험은 전부 "심사관이 실제로 재현해 보인 사고"를 그대로 다시 일으켜,
같은 사고가 다시 나면 즉시 빨간불이 켜지게 하는 것이 목적이다.
"""

from datetime import UTC, datetime, timedelta

import httpx
import pytest
import respx

from domainchecker.analyze.scoring import judge
from domainchecker.clients import http_reason, openpagerank, serper
from domainchecker.models import CheckState, CheckStatus, DomainResult
from domainchecker.pipeline import is_stale
from domainchecker.report import html as report_html

OK = CheckState(status=CheckStatus.OK)


@pytest.fixture
async def http():
    async with httpx.AsyncClient() as client:
        yield client


# ── 권위 점수 조회가 검사 전체를 죽이던 문제 ─────────────────────────────
@respx.mock
async def test_authority_lookup_never_kills_the_run(http):
    """OPR 응답이 어긋나면 예외가 밖으로 나와 도메인 1,000개가 통째로 죽었다."""
    respx.get("https://openpagerank.com/api/v1.0/getPageRank").mock(
        return_value=httpx.Response(200, json=["엉뚱한 모양"])
    )
    found = await openpagerank.fetch_batch(["a.com"], "key", http)
    assert found["a.com"].check.status is CheckStatus.UNCHECKED


@respx.mock
async def test_authority_row_with_text_status_code_is_survivable(http):
    """status_code 자리에 숫자가 아닌 글자가 와도 int() 로 터지면 안 된다."""
    respx.get("https://openpagerank.com/api/v1.0/getPageRank").mock(
        return_value=httpx.Response(
            200, json={"response": [{"domain": "a.com", "status_code": "ok"}]}
        )
    )
    found = await openpagerank.fetch_batch(["a.com"], "key", http)
    assert found["a.com"].has_data is False
    assert found["a.com"].page_rank == 0.0


@respx.mock
async def test_authority_without_data_is_not_reported_as_zero(http):
    """자료가 없는 것을 0.00 으로 보여 주면 '권위 0인 나쁜 도메인'으로 읽힌다."""
    respx.get("https://openpagerank.com/api/v1.0/getPageRank").mock(
        return_value=httpx.Response(
            200, json={"response": [{"domain": "new.com", "status_code": 404}]}
        )
    )
    found = await openpagerank.fetch_batch(["new.com"], "key", http)
    assert found["new.com"].has_data is False

    result = DomainResult(domain="new.com", authority=found["new.com"])
    fragment = report_html.detail_fragment(result)
    assert "0.00 / 10" not in fragment
    assert "자료 없음" in fragment


# ── 색인 오염 오탐 ────────────────────────────────────────────────────
@pytest.mark.parametrize(
    "title",
    [
        "성인 자격증 교육원 · 평생교육",
        "성인병 예방 건강검진센터",
        "XXXL 사이즈 등산복 전문",
        "Escorted tours of Ireland",
    ],
)
def test_legal_wording_is_not_treated_as_contamination(title):
    """오염어 하나가 곧바로 '제외' 치명 사유라, 오탐은 멀쩡한 도메인을 죽인다."""
    assert serper.contamination_hits(title) == []


@pytest.mark.parametrize(
    "title",
    ["온라인 카지노 먹튀 검증", "Buy viagra online no prescription", "성인용품 쇼핑몰"],
)
def test_real_contamination_is_still_caught(title):
    assert serper.contamination_hits(title)


# ── 오류 번호를 사람 말로 ──────────────────────────────────────────────
def test_http_errors_are_explained_in_plain_korean():
    assert "키가 틀렸습니다" in http_reason(401)
    assert "돈이 떨어졌습니다" in http_reason(402)
    assert "횟수를 다 썼습니다" in http_reason(429)
    assert "429" in http_reason(429)  # 번호는 문의용으로 남긴다


# ── 점수 미달인데 노랑으로 나가던 문제 ──────────────────────────────────
def test_score_below_cut_says_so_even_when_a_required_check_is_missing():
    """16점짜리가 '사면 안 되는 이유: 없음'인 노란 도장으로 나가면 사용자가 돈을 잃는다."""
    result = DomainResult(domain="junk.com")
    result.wayback.check = OK
    result.wayback.total_captures = 20
    result.wayback.first_seen = "20100101000000"
    result.wayback.last_seen = "20240101000000"
    for part in ("registration", "index", "ai", "authority", "rules"):
        getattr(result, part).check = OK
    result.rules.doorway = True
    result.rules.hidden_text = True
    result.rules.link_farm = True
    result.rules.autogenerated = True
    result.rules.parking_ratio = 0.8
    result.spamhaus.check = CheckState(status=CheckStatus.UNCHECKED, note="조회 차단")

    judge(result)
    assert result.score < 50
    assert any("사실상 제외 대상" in reason for reason in result.warn_reasons)


# ── 못 한 검사가 "깨끗함"으로 읽히던 문제 ───────────────────────────────
def test_rule_check_failure_shows_up_instead_of_reading_as_clean():
    result = DomainResult(domain="norules.com")
    result.rules.check = CheckState(
        status=CheckStatus.UNCHECKED, note="본문을 가져온 스냅샷이 없어 규칙 검사를 못 했습니다."
    )
    judge(result)

    assert "운영방식 규칙 검사" in " ".join(result.unchecked)
    fragment = report_html.detail_fragment(result)
    assert "특별한 흔적 없음" not in fragment
    assert "규칙 검사를 못 했습니다" in fragment


def test_blacklist_checks_that_never_ran_say_so():
    result = DomainResult(domain="skipped.com")
    result.safebrowsing.check = CheckState(status=CheckStatus.NOT_RUN)
    result.virustotal.check = CheckState(status=CheckStatus.NOT_RUN)

    fragment = report_html.detail_fragment(result)
    assert "브라우징: -" not in fragment
    assert "깨끗하다는 뜻이 아닙니다" in fragment


# ── 묵은 저장분을 오늘 것처럼 쓰던 문제 ─────────────────────────────────
def test_old_cached_results_are_rechecked():
    fresh = {"finished_at": datetime.now(UTC).isoformat(timespec="seconds")}
    old = {"finished_at": (datetime.now(UTC) - timedelta(days=30)).isoformat(timespec="seconds")}

    assert is_stale(fresh, 7) is False
    assert is_stale(old, 7) is True
    assert is_stale({"finished_at": ""}, 7) is True  # 언제인지 모르면 믿지 않는다
    assert is_stale(old, 0) is False  # 0이면 무기한 보관


# ── 보고서 위생 ───────────────────────────────────────────────────────
def test_report_stamps_the_date_and_links_the_raw_file_next_to_it(tmp_path):
    result = DomainResult(domain="example.com", finished_at="2026-08-06T11:42:00+00:00")
    index = report_html.write_report([result], tmp_path)
    page = index.read_text(encoding="utf-8")

    assert "2026년 8월 6일" in page
    assert 'href="results.json"' in page
    assert (index.parent / "results.json").exists()


def test_report_drops_pages_left_over_from_an_earlier_run(tmp_path):
    report_dir = tmp_path / "report"
    report_dir.mkdir()
    stale = report_dir / "gone.com.html"
    stale.write_text("옛날 것", encoding="utf-8")

    report_html.write_report([DomainResult(domain="example.com")], tmp_path)
    assert not stale.exists()
    assert (report_dir / "example.com.html").exists()


# ── 접속 비밀번호 검사가 터지던 문제 ────────────────────────────────────
def test_password_gate_rejects_a_non_ascii_header_without_crashing(monkeypatch, tmp_path):
    from fastapi.testclient import TestClient

    from domainchecker.server import create_app

    monkeypatch.setenv("DOMAINCHECKER_PASSWORD", "비밀")
    monkeypatch.chdir(tmp_path)
    client = TestClient(create_app())

    assert client.get("/api/status", headers={"Authorization": "Basic zzzz"}).status_code == 401
    # 아스키가 아닌 바이트가 와도 500 이 아니라 401 로 막혀야 한다
    bad = client.get("/api/status", headers={b"Authorization": b"Basic \xed\x95\x9c"})
    assert bad.status_code == 401
