from domainchecker.analyze.extract import SnapshotContent
from domainchecker.analyze.rules import analyze, brand_hits
from domainchecker.models import CheckStatus

VOCAB_BAKERY = (
    ["빵집", "반죽", "발효", "오븐", "통밀", "버터", "우유", "소금", "설탕", "계량", "온도", "습도", "손님", "아침", "진열", "포장", "향기", "식빵", "크루아상", "바게트"]
)
VOCAB_HIKING = (
    ["등산", "배낭", "지도", "나침반", "텐트", "침낭", "코스", "정상", "능선", "계곡", "물통", "간식", "날씨", "바람", "안개", "장갑", "스틱", "발목", "사진", "기록"]
)


def prose(vocab: list[str], lines: int = 20) -> str:
    """Varied text: every word appears about 5% of the time, like real writing."""
    return " ".join(
        " ".join(vocab[(i + j) % len(vocab)] for j in range(10)) + "." for i in range(lines)
    )


def snap(timestamp="20150101000000", **kwargs) -> SnapshotContent:
    base = {"text": prose(VOCAB_BAKERY), "lang": "ko"}
    base.update(kwargs)
    return SnapshotContent(timestamp=timestamp, **base)


def test_clean_site_triggers_nothing():
    findings = analyze(
        [
            snap("20150101000000", text=prose(VOCAB_BAKERY)),
            snap("20190101000000", text=prose(VOCAB_HIKING)),
        ],
        "bakery.com",
    )
    assert findings.check.status is CheckStatus.OK
    assert findings.spam_operation is False
    assert findings.sensitive_terms == []


def test_no_readable_snapshot_is_unchecked():
    findings = analyze([SnapshotContent(timestamp="20150101000000", fetched=False)], "x.com")
    assert findings.check.status is CheckStatus.UNCHECKED
    assert findings.spam_operation is False


def test_hidden_text_is_flagged():
    findings = analyze([snap(hidden_marks=["display:none"])], "x.com")
    assert findings.hidden_text is True
    assert findings.spam_operation is True
    assert findings.evidence


def test_link_farm_is_flagged():
    findings = analyze([snap(external_links=120, external_hosts=45)], "x.com")
    assert findings.link_farm is True


def test_keyword_stuffing_is_doorway():
    findings = analyze([snap(text="대출 " * 200 + "안내입니다.")], "x.com")
    assert findings.doorway is True


def test_comma_separated_keyword_list_is_doorway():
    findings = analyze([snap(text="강남 대출, 부산 대출, 대구 대출, 인천 대출, 광주 대출, 대전 대출, 울산 대출, 세종 대출, 제주 대출, 수원 대출")], "x.com")
    assert findings.doorway is True


def test_repeated_identical_pages_look_autogenerated():
    body = prose(VOCAB_BAKERY)
    findings = analyze(
        [snap("20140101000000", text=body), snap("20180101000000", text=body)], "x.com"
    )
    assert findings.autogenerated is True


def test_parking_ratio_excludes_parked_pages_from_rules():
    findings = analyze(
        [
            snap("20140101000000", parking=True, text="This domain is for sale"),
            snap("20180101000000"),
        ],
        "x.com",
    )
    assert findings.parking_ratio == 0.5
    assert findings.spam_operation is False


def test_sensitive_terms_are_advisory_only():
    findings = analyze([snap(text="합법 카지노 산업 뉴스를 다룹니다. " * 10)], "news.com")
    assert any("도박" in term for term in findings.sensitive_terms)
    assert findings.spam_operation is False  # 업종 낱말만으로는 스팸이 아니다


def test_language_shift_is_detected():
    findings = analyze(
        [
            snap("20120101000000", lang="ko"),
            snap("20200101000000", lang="ru", text="Это текст на русском языке. " * 10),
        ],
        "x.com",
    )
    assert findings.language_shift is True


def test_brand_hits_in_domain_name():
    assert brand_hits("cheap-nike-shoes.com") == ["nike"]
    assert brand_hits("nike.com") == []  # 상표권자 본인 도메인은 제외
    assert brand_hits("bakery.com") == []
