"""적대 심사(품질 심사관·진상 고객)에서 나온 결함의 회귀 시험.

여기 있는 시험은 전부 "심사관이 실제로 재현해 보인 사고"를 그대로 다시 일으켜,
같은 사고가 다시 나면 즉시 빨간불이 켜지게 하는 것이 목적이다.
"""

from datetime import UTC, datetime, timedelta

from domainchecker.analyze.scoring import judge
from domainchecker.clients import http_reason
from domainchecker.models import CheckState, CheckStatus, DomainResult
from domainchecker.pipeline import ENGINE_VERSION, is_stale
from domainchecker.report import html as report_html

OK = CheckState(status=CheckStatus.OK)


# ── 오류 번호를 사람 말로 ──────────────────────────────────────────────
def test_http_errors_are_explained_in_plain_korean():
    assert "키가 틀렸습니다" in http_reason(401)
    assert "돈이 떨어졌습니다" in http_reason(402)
    assert "횟수를 다 썼습니다" in http_reason(429)
    assert "429" in http_reason(429)  # 번호는 문의용으로 남긴다


# ── 쓰레기 도메인이 노랑으로 나가던 문제 ────────────────────────────────
def test_junk_domain_is_rejected_even_when_a_required_check_is_missing():
    """스팸 흔적 4종짜리가 '사면 안 되는 이유: 없음'인 노랑으로 나가면 돈을 잃는다.

    지금은 기계 거부권(흔적 3종 이상 = 확정 제외)이 필수 검사 하나가 비어도 그대로
    작동한다 — 예전 '점수 미달' 경고 문구보다 강한 빨간 도장이다.
    """
    result = DomainResult(domain="junk.com")
    result.wayback.check = OK
    result.wayback.total_captures = 20
    result.wayback.first_seen = "20100101000000"
    result.wayback.last_seen = "20240101000000"
    for part in ("registration", "index", "ai", "rules"):
        getattr(result, part).check = OK
    result.rules.doorway = True
    result.rules.hidden_text = True
    result.rules.link_farm = True
    result.rules.autogenerated = True
    result.rules.parking_ratio = 0.8
    result.spamhaus.check = CheckState(status=CheckStatus.UNCHECKED, note="조회 차단")

    judge(result)
    assert result.verdict.value == "REJECT"
    assert any("기계적 검사만으로도 확정" in reason for reason in result.fatal_reasons)


# ── 못 한 검사가 "깨끗함"으로 읽히던 문제 ───────────────────────────────
def test_rule_check_failure_shows_up_instead_of_reading_as_clean():
    result = DomainResult(domain="norules.com")
    result.rules.check = CheckState(
        status=CheckStatus.UNCHECKED, note="본문을 가져온 스냅샷이 없어 규칙 검사를 못 했습니다."
    )
    judge(result)

    assert "운영방식 규칙 검사" in " ".join(result.unchecked)
    fragment = report_html.detail_fragment(result)
    assert "특별한 흔적 없음" not in fragment
    assert "규칙 검사를 못 했습니다" in fragment


def test_blacklist_checks_that_never_ran_say_so():
    result = DomainResult(domain="skipped.com")
    result.safebrowsing.check = CheckState(status=CheckStatus.NOT_RUN)

    fragment = report_html.detail_fragment(result)
    assert "브라우징: -" not in fragment
    assert "깨끗하다는 뜻이 아닙니다" in fragment


# ── 묵은 저장분을 오늘 것처럼 쓰던 문제 ─────────────────────────────────
def test_old_cached_results_are_rechecked():
    now = datetime.now(UTC).isoformat(timespec="seconds")
    fresh = {"finished_at": now, "engine": ENGINE_VERSION}
    old = {
        "finished_at": (datetime.now(UTC) - timedelta(days=30)).isoformat(timespec="seconds"),
        "engine": ENGINE_VERSION,
    }

    assert is_stale(fresh, 7) is False
    assert is_stale(old, 7) is True
    assert is_stale({"finished_at": "", "engine": ENGINE_VERSION}, 7) is True  # 언제인지 모르면 믿지 않는다
    assert is_stale(old, 0) is False  # 0이면 무기한 보관


def test_results_from_an_older_check_engine_are_rechecked():
    """검사 방식이 바뀌었으면 '키가 없어 못 했습니다'라고 적힌 저장분을 버려야 한다."""
    now = datetime.now(UTC).isoformat(timespec="seconds")

    assert is_stale({"finished_at": now}, 7) is True  # 번호가 아예 없는 옛 저장분
    assert is_stale({"finished_at": now, "engine": ENGINE_VERSION - 1}, 7) is True
    assert is_stale({"finished_at": now, "engine": "망가짐"}, 0) is True
    assert is_stale({"finished_at": now, "engine": ENGINE_VERSION}, 7) is False


# ── 보고서 위생 ───────────────────────────────────────────────────────
def test_report_stamps_the_date_and_links_the_raw_file_next_to_it(tmp_path):
    result = DomainResult(domain="example.com", finished_at="2026-08-06T11:42:00+00:00")
    index = report_html.write_report([result], tmp_path)
    page = index.read_text(encoding="utf-8")

    assert "2026년 8월 6일" in page
    assert 'href="results.json"' in page
    assert (index.parent / "results.json").exists()


def test_report_drops_pages_left_over_from_an_earlier_run(tmp_path):
    report_dir = tmp_path / "report"
    report_dir.mkdir()
    stale = report_dir / "gone.com.html"
    stale.write_text("옛날 것", encoding="utf-8")

    report_html.write_report([DomainResult(domain="example.com")], tmp_path)
    assert not stale.exists()
    assert (report_dir / "example.com.html").exists()


# ── 아주 긴 도메인은 지워도 사진만 남던 문제 ─────────────────────────────
def test_a_very_long_domain_names_its_cache_and_its_photos_the_same_way():
    """이름을 다듬는 자리가 세 군데라 자르는 길이가 어긋나 있었다.

    저장분은 120자로, 화면 사진은 100자로 잘랐다. 지우기는 저장분 이름으로
    사진을 찾기 때문에(`{stem}_*.png`), 100자가 넘는 긴 도메인은 결과를 지워도
    사진이 통째로 남았다. 이제 다듬는 자리가 한 곳뿐이라 둘이 늘 맞는다.
    """
    from domainchecker.cache import safe_name
    from domainchecker.capture import _filename

    long_domain = "a" * 130 + ".com"
    stem = safe_name(long_domain)
    photo = _filename(long_domain, "20240101000000")
    # 지우기가 쓰는 바로 그 짝 맞추기
    assert photo.startswith(f"{stem}_"), "사진 이름이 저장분 이름으로 시작해야 지우기가 찾는다"
    assert len(stem) == 120


def test_result_without_wayback_history_is_stale():
    """웨이백을 못 읽은 반쪽 결과는 7일 믿지 않는다 — 다음 분석 때 다시 검사한다."""
    now = datetime.now(UTC).isoformat(timespec="seconds")
    broken = {"finished_at": now, "engine": ENGINE_VERSION,
              "wayback": {"check": {"status": "UNCHECKED", "note": "웨이백 응답 오류(503)."}}}
    fine = {"finished_at": now, "engine": ENGINE_VERSION,
            "wayback": {"check": {"status": "OK", "note": ""}}}
    assert is_stale(broken, 7) is True
    assert is_stale(fine, 7) is False

