"""Archived HTML -> readable text, parking detection, rough language detection."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from bs4 import BeautifulSoup

TEXT_LIMIT = 6_000

_DROP_TAGS = ("script", "style", "noscript", "template", "svg", "iframe")
_WS = re.compile(r"\s+")
_HSPACE = re.compile(r"[^\S\n]+")  # 줄바꿈만 빼고 접는다

# ── 파킹(‘도메인 팝니다’ 빈 화면) 표지 — 온 저장소에서 이 한 벌만 쓴다 ──────────
# 예전에는 같은 판정을 이 파일과 clients/freeindex.py 가 각각 다른 목록으로 따로
# 했다. 실측(2026-08-23, 같은 입력 9개)에서 두 벌이 5개에 서로 다른 답을 냈고,
# 이쪽 목록은 멀쩡한 사이트 3개를 파킹으로 잘못 찍었다. 한 벌로 합치고, 뜻을
# 넘겨짚던 낱말은 아래 ③처럼 구조 조건과 묶었다.

# ① 이것만 나와도 파킹이 확실한 문구. 사람이 읽으라고 쓴 글에는 나오지 않는다.
PARKING_PHRASES = (
    "this domain is for sale",
    "this domain may be for sale",
    "domain is for sale",
    "buy this domain",
    "domain for sale",
    "domain parking",
    "parking page",
    "parked free",
    "parked domain",
    "this webpage was generated by the domain owner",
    "이 도메인을 구매",
    "이 도메인은 판매",
    "도메인 판매",
    "도메인이 판매",
    "도메인 팝니다",
    "판매 중인 도메인",
    "このドメインは",
    "该域名",
)

# ② 도메인 판매·주차 업체. 이름을 본문 산문에서 찾으면 "저희 고객사에 afternic 도
#    있습니다" 같은 멀쩡한 문장이 걸린다(실측 오차단 1건). 그래서 글이 아니라
#    **주소 자리**에서만 본다.
PARKING_VENDORS = (
    "sedo.com",
    "sedoparking.com",
    "afternic.com",
    "dan.com",
    "hugedomains.com",
    "bodis.com",
    "parkingcrew.net",
    "parklogic.com",
    "above.com",
    "undeveloped.com",
    "domainmarket.com",
    "buydomains.com",
    "namedrive.com",
    "skenzo.com",
    "voodoo.com",
)

# ③ 혼자서는 아무 뜻이 없는 표지. "관련 검색어"는 네이버 블로그가, "related
#    searches"는 영문 뉴스가 늘 달고 있는 위젯이라, 하나만 보고 파킹이라 하면
#    멀쩡한 사이트를 때린다(실측 오차단 2건). 그래서 **글이 거의 없고 + 이런 표지가
#    둘 이상 겹칠 때만** 센다 — 블로그는 위젯을 하나 달지만, 광고만 있는 파킹
#    화면은 이런 딱지를 여러 개 겹쳐 놓는다. 이 저장소가 이미 쓰는 방식과 같다
#    (규칙 흔적도 3종이 겹쳐야 확정으로 본다 — scoring.RULES_FATAL_HITS).
WEAK_PARKING_MARKS = ("관련 검색어", "related searches", "sponsored listings", "for sale")
WEAK_BODY_LIMIT = 400
WEAK_MARKS_NEEDED = 2

_HIDDEN_PATTERNS = (
    re.compile(r"display\s*:\s*none", re.IGNORECASE),
    re.compile(r"visibility\s*:\s*hidden", re.IGNORECASE),
    re.compile(r"font-size\s*:\s*0(?:px|em|pt)?\b", re.IGNORECASE),
    re.compile(r"text-indent\s*:\s*-\s*\d{3,}", re.IGNORECASE),
    re.compile(r"position\s*:\s*absolute\s*;[^\"']*(?:left|top)\s*:\s*-\s*\d{3,}", re.IGNORECASE),
    re.compile(r"color\s*:\s*#?(?:fff(?:fff)?|white)\b[^\"']*background(?:-color)?\s*:\s*#?(?:fff(?:fff)?|white)", re.IGNORECASE),
)

_HANGUL = re.compile(r"[가-힣]")
_KANA = re.compile(r"[぀-ヿ]")
_HAN = re.compile(r"[一-鿿]")
_CYRILLIC = re.compile(r"[Ѐ-ӿ]")
_LATIN = re.compile(r"[A-Za-z]")

LANG_LABEL = {
    "ko": "한국어",
    "ja": "일본어",
    "zh": "중국어",
    "ru": "러시아어",
    "en": "영어",
    "unknown": "알 수 없음",
}


@dataclass
class SnapshotContent:
    """One archived page, reduced to what the rules and the AI actually read.

    화면 글자는 두 갈래로 나눠 담는다. `text` 는 화면에 보이는 글 전부(링크 글귀
    포함)고, `body_text` 는 **사람이 읽으라고 쓴 글**만 남긴 것이다. 목록(index)
    화면은 글자의 거의 전부가 링크 글귀라, 하나로 납작하게 붙여 두면 "같은 낱말이
    39%인 글"로 보인다 — 그 납작한 글을 규칙 검사와 AI가 둘 다 받으므로 둘이
    **같은 원인으로 함께 속고**, "둘 다 동의하면 확실하다"는 안전장치가 무너진다
    (실측 2026-08-23: photodiary.co.kr 2001년 '선생님께' 목록이 REJECT).
    """

    timestamp: str
    url: str = ""
    title: str = ""
    text: str = ""
    body_text: str = ""
    lang: str = "unknown"
    parking: bool = False
    parking_marks: list[str] = field(default_factory=list)
    hidden_marks: list[str] = field(default_factory=list)
    external_links: int = 0
    internal_links: int = 0
    external_hosts: int = 0
    link_texts: list[str] = field(default_factory=list)
    link_targets: list[str] = field(default_factory=list)
    fetched: bool = True

    @property
    def year(self) -> int:
        return int(self.timestamp[:4]) if self.timestamp[:4].isdigit() else 0

    @property
    def links(self) -> set[tuple[str, str]]:
        """서로 다른 링크 = (글귀, 목적지) 짝의 모음.

        게시판 목록은 같은 글귀가 **같은 주소**를 가리키며 수십 줄 그려지기도 한다
        (photodiary 2001년 목록: '홍선생님께' 28줄이 전부 같은 주소). 그건 목록의
        생김새지 도어웨이가 아니므로 한 개로 센다. 목적지를 모르는 채 만든 것은
        전부 같은 곳으로 보고 한 개로 접는다 — 모르면 안 때리는 쪽이 맞다.
        """
        targets = (list(self.link_targets) + [""] * len(self.link_texts))[: len(self.link_texts)]
        return {
            (label.strip().lower(), target)
            for label, target in zip(self.link_texts, targets, strict=True)
        }


def _readable_soup(html: str) -> BeautifulSoup:
    """Parse once, drop the tags whose contents are never shown to a reader."""
    soup = BeautifulSoup(html, "lxml")
    for tag in soup(list(_DROP_TAGS)):
        tag.decompose()
    return soup


def _flatten(soup: BeautifulSoup) -> str:
    return _WS.sub(" ", soup.get_text(" ", strip=True)).strip()


def _by_lines(soup: BeautifulSoup) -> str:
    """본문을 화면의 줄 단위로 남긴다(줄바꿈은 살리고 가로 여백만 접는다).

    줄을 뭉개면 "같은 줄이 서른 번 그려진 목록"과 "한 낱말을 서른 번 박아 넣은 글"이
    똑같이 보인다. 앞은 멀쩡한 목록이고 뒤는 키워드 채우기다 — 줄을 살려 둬야
    도어웨이 검사가 같은 줄을 한 번만 세고 둘을 가를 수 있다.
    """
    lines = [_HSPACE.sub(" ", line).strip() for line in soup.get_text("\n").split("\n")]
    return "\n".join(line for line in lines if line)


def extract_text(html: str, limit: int = TEXT_LIMIT) -> str:
    """Visible body text, whitespace collapsed and capped (link labels included)."""
    if not html:
        return ""
    return _flatten(_readable_soup(html))[:limit]


def extract_body_text(html: str, limit: int = TEXT_LIMIT) -> str:
    """링크 글귀를 뺀 글 — 사람이 읽으라고 쓴 부분만.

    목록 화면에서는 이 값이 거의 비는데, 그게 정답이다: "읽을 글은 거의 없고 목록만
    있다"는 사실이 그대로 드러나야 낱말 편중 규칙이 목록을 때리지 않는다.
    """
    if not html:
        return ""
    soup = _readable_soup(html)
    for anchor in soup.find_all("a", href=True):
        anchor.decompose()
    return _by_lines(soup)[:limit]


def detect_language(text: str) -> str:
    """Script-ratio heuristic — enough to spot a language switch across years."""
    sample = text[:4000]
    counts = {
        "ko": len(_HANGUL.findall(sample)),
        "ja": len(_KANA.findall(sample)),
        "zh": len(_HAN.findall(sample)),
        "ru": len(_CYRILLIC.findall(sample)),
        "en": len(_LATIN.findall(sample)),
    }
    total = sum(counts.values())
    if total < 30:
        return "unknown"
    # 일본어는 한자를 함께 쓰므로 가나가 있으면 일본어로 본다.
    if counts["ja"] / total > 0.05:
        return "ja"
    if counts["ko"] / total > 0.10:
        return "ko"
    if counts["zh"] / total > 0.10:
        return "zh"
    if counts["ru"] / total > 0.10:
        return "ru"
    return "en" if counts["en"] / total > 0.5 else "unknown"


def parking_marks(text: str, html: str = "", body_text: str | None = None) -> list[str]:
    """파킹으로 볼 표지를 모은다 — 저장소 전체가 쓰는 단 하나의 파킹 판정기.

    확실한 문구(①)는 글에서든 코드에서든 찾고, 판매 업체 이름(②)은 주소 자리에서만
    찾고, 뜻이 넓은 표지(③)는 원래 글이 거의 없을 때만 센다.

    "글이 거의 없다"는 **링크 글귀를 뺀 글**(`body_text`)로 잰다. 광고만 깔린 파킹
    화면은 글자의 거의 전부가 광고 링크라, 링크 글귀까지 합쳐 재면 "글이 400자를
    넘는다"가 되어 이 검사가 통째로 건너뛰어졌다 — 진짜 파킹을 놓치던 자리다.

    이 판정은 기계가 문구로 **짐작**하는 것이다. 키가 있으면 AI 가 본문을 직접 읽고
    최종 판단을 하며, 키가 없을 때는 이 짐작이 그대로 폴백으로 남는다.
    """
    body = (text or "").lower()
    marks = {p for p in PARKING_PHRASES if p in body}
    if html:
        markup = html[:20000].lower()
        marks |= {p for p in PARKING_PHRASES if p in markup}
        # 주소 자리에서만 — "//sedo.com" 또는 "//www.sedo.com" 같은 꼴.
        marks |= {v for v in PARKING_VENDORS if f"//{v}" in markup or f".{v}" in markup}
    # 글은 없고 광고 딱지만 여러 개 붙어 있는 화면.
    prose = body if body_text is None else (body_text or "").lower()
    if len(prose) < WEAK_BODY_LIMIT:
        weak = {m for m in WEAK_PARKING_MARKS if m in body}
        if len(weak) >= WEAK_MARKS_NEEDED:
            marks |= weak
    return sorted(marks)


def is_parking(html: str, text: str, body_text: str | None = None) -> tuple[bool, list[str]]:
    """A parking/for-sale placeholder is not real site history."""
    marks = parking_marks(text, html, body_text)
    return bool(marks), marks


def parse_snapshot(
    html: str,
    timestamp: str,
    url: str = "",
    limit: int = TEXT_LIMIT,
    base_domain: str = "",
) -> SnapshotContent:
    """Turn one archived page into the structure the analyzers consume.

    `base_domain` decides what counts as an external link — the playback URL
    itself lives on web.archive.org, so it must not be used as the host.
    """
    content = SnapshotContent(timestamp=timestamp, url=url, fetched=bool(html))
    if not html:
        return content
    soup = _readable_soup(html)
    if soup.title and soup.title.string:
        content.title = _WS.sub(" ", soup.title.string).strip()[:200]

    host = (base_domain or "").lower().removeprefix("www.")
    anchors = soup.find_all("a", href=True)
    for anchor in anchors:
        href = anchor["href"].strip()
        label = _WS.sub(" ", anchor.get_text(" ", strip=True))[:80]
        if label:
            content.link_texts.append(label)
            content.link_targets.append(href.lower()[:200])
        target = _host_of(href)
        if target and target != host:
            content.external_links += 1
        else:
            content.internal_links += 1
    content.external_hosts = len({_host_of(a["href"]) for a in anchors} - {"", host})

    for pattern in _HIDDEN_PATTERNS:
        found = pattern.search(html)
        if found:
            content.hidden_marks.append(found.group(0)[:60])

    # 같은 soup 을 두 번 쓴다 — 먼저 화면 글자 전부를 뜨고, 링크를 걷어낸 뒤 본문만 뜬다.
    content.text = _flatten(soup)[:limit]
    for anchor in anchors:
        anchor.decompose()
    content.body_text = _by_lines(soup)[:limit]

    # 언어는 사람이 쓴 글로 본다. 목록 화면처럼 글이 거의 없어 못 가리면 그때만
    # 링크 글귀까지 합쳐 다시 본다(차림표가 영어라고 영어 사이트로 찍지 않게).
    content.lang = detect_language(content.body_text)
    if content.lang == "unknown":
        content.lang = detect_language(content.text)
    content.parking, content.parking_marks = is_parking(html, content.text, content.body_text)
    return content


def _host_of(url: str) -> str:
    match = re.match(r"^(?:[a-z][a-z0-9+.\-]*:)?//([^/?#]+)", (url or "").strip(), re.IGNORECASE)
    if not match:
        return ""
    host = match.group(1).split("@")[-1].split(":")[0].lower()
    # Wayback playback URLs embed the original host after the timestamp.
    return host.removeprefix("www.")


def snapshot_from_page(page: dict, base_domain: str = "", limit: int = TEXT_LIMIT) -> SnapshotContent:
    """Build a SnapshotContent from a WaybackHistory.pages entry."""
    content = parse_snapshot(
        page.get("html", ""),
        page.get("timestamp", ""),
        page.get("url", ""),
        limit,
        base_domain,
    )
    content.fetched = bool(page.get("fetched"))
    return content
