"""Archived HTML -> readable text, parking detection, rough language detection."""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from bs4 import BeautifulSoup

TEXT_LIMIT = 6_000

_DROP_TAGS = ("script", "style", "noscript", "template", "svg", "iframe")
_WS = re.compile(r"\s+")

PARKING_PATTERNS = (
    "this domain is for sale",
    "domain is for sale",
    "buy this domain",
    "domain for sale",
    "이 도메인을 구매",
    "도메인 판매",
    "도메인이 판매",
    "parked free",
    "domain parking",
    "parked domain",
    "this webpage was generated by the domain owner",
    "sedoparking",
    "afternic",
    "dan.com",
    "hugedomains",
    "관련 검색어",
    "related searches",
    "sponsored listings",
    "このドメインは",
    "该域名",
)

_HIDDEN_PATTERNS = (
    re.compile(r"display\s*:\s*none", re.IGNORECASE),
    re.compile(r"visibility\s*:\s*hidden", re.IGNORECASE),
    re.compile(r"font-size\s*:\s*0(?:px|em|pt)?\b", re.IGNORECASE),
    re.compile(r"text-indent\s*:\s*-\s*\d{3,}", re.IGNORECASE),
    re.compile(r"position\s*:\s*absolute\s*;[^\"']*(?:left|top)\s*:\s*-\s*\d{3,}", re.IGNORECASE),
    re.compile(r"color\s*:\s*#?(?:fff(?:fff)?|white)\b[^\"']*background(?:-color)?\s*:\s*#?(?:fff(?:fff)?|white)", re.IGNORECASE),
)

_HANGUL = re.compile(r"[가-힣]")
_KANA = re.compile(r"[぀-ヿ]")
_HAN = re.compile(r"[一-鿿]")
_CYRILLIC = re.compile(r"[Ѐ-ӿ]")
_LATIN = re.compile(r"[A-Za-z]")

LANG_LABEL = {
    "ko": "한국어",
    "ja": "일본어",
    "zh": "중국어",
    "ru": "러시아어",
    "en": "영어",
    "unknown": "알 수 없음",
}


@dataclass
class SnapshotContent:
    """One archived page, reduced to what the rules and the AI actually read."""

    timestamp: str
    url: str = ""
    title: str = ""
    text: str = ""
    lang: str = "unknown"
    parking: bool = False
    parking_marks: list[str] = field(default_factory=list)
    hidden_marks: list[str] = field(default_factory=list)
    external_links: int = 0
    internal_links: int = 0
    external_hosts: int = 0
    link_texts: list[str] = field(default_factory=list)
    fetched: bool = True

    @property
    def year(self) -> int:
        return int(self.timestamp[:4]) if self.timestamp[:4].isdigit() else 0


def extract_text(html: str, limit: int = TEXT_LIMIT) -> str:
    """Visible body text, whitespace collapsed and capped."""
    if not html:
        return ""
    soup = BeautifulSoup(html, "lxml")
    for tag in soup(list(_DROP_TAGS)):
        tag.decompose()
    text = _WS.sub(" ", soup.get_text(" ", strip=True)).strip()
    return text[:limit]


def detect_language(text: str) -> str:
    """Script-ratio heuristic — enough to spot a language switch across years."""
    sample = text[:4000]
    counts = {
        "ko": len(_HANGUL.findall(sample)),
        "ja": len(_KANA.findall(sample)),
        "zh": len(_HAN.findall(sample)),
        "ru": len(_CYRILLIC.findall(sample)),
        "en": len(_LATIN.findall(sample)),
    }
    total = sum(counts.values())
    if total < 30:
        return "unknown"
    # 일본어는 한자를 함께 쓰므로 가나가 있으면 일본어로 본다.
    if counts["ja"] / total > 0.05:
        return "ja"
    if counts["ko"] / total > 0.10:
        return "ko"
    if counts["zh"] / total > 0.10:
        return "zh"
    if counts["ru"] / total > 0.10:
        return "ru"
    return "en" if counts["en"] / total > 0.5 else "unknown"


def is_parking(html: str, text: str) -> tuple[bool, list[str]]:
    """A parking/for-sale placeholder is not real site history."""
    haystack = f"{text} {html[:20000]}".lower()
    marks = sorted({p for p in PARKING_PATTERNS if p in haystack})
    if marks:
        return True, marks
    # 본문이 거의 없고 링크만 몇 개인 자리표시 페이지도 파킹으로 본다.
    if text and len(text) < 200 and "for sale" in haystack:
        return True, ["for sale"]
    return False, []


def parse_snapshot(
    html: str,
    timestamp: str,
    url: str = "",
    limit: int = TEXT_LIMIT,
    base_domain: str = "",
) -> SnapshotContent:
    """Turn one archived page into the structure the analyzers consume.

    `base_domain` decides what counts as an external link — the playback URL
    itself lives on web.archive.org, so it must not be used as the host.
    """
    content = SnapshotContent(timestamp=timestamp, url=url, fetched=bool(html))
    if not html:
        return content
    soup = BeautifulSoup(html, "lxml")
    if soup.title and soup.title.string:
        content.title = _WS.sub(" ", soup.title.string).strip()[:200]

    host = (base_domain or "").lower().removeprefix("www.")
    for anchor in soup.find_all("a", href=True):
        href = anchor["href"].strip()
        label = _WS.sub(" ", anchor.get_text(" ", strip=True))[:80]
        if label:
            content.link_texts.append(label)
        target = _host_of(href)
        if target and target != host:
            content.external_links += 1
        else:
            content.internal_links += 1
    content.external_hosts = len({_host_of(a["href"]) for a in soup.find_all("a", href=True)} - {"", host})

    for pattern in _HIDDEN_PATTERNS:
        found = pattern.search(html)
        if found:
            content.hidden_marks.append(found.group(0)[:60])

    content.text = extract_text(html, limit)
    content.lang = detect_language(content.text)
    content.parking, content.parking_marks = is_parking(html, content.text)
    return content


def _host_of(url: str) -> str:
    match = re.match(r"^(?:[a-z][a-z0-9+.\-]*:)?//([^/?#]+)", (url or "").strip(), re.IGNORECASE)
    if not match:
        return ""
    host = match.group(1).split("@")[-1].split(":")[0].lower()
    # Wayback playback URLs embed the original host after the timestamp.
    return host.removeprefix("www.")


def snapshot_from_page(page: dict, base_domain: str = "", limit: int = TEXT_LIMIT) -> SnapshotContent:
    """Build a SnapshotContent from a WaybackHistory.pages entry."""
    content = parse_snapshot(
        page.get("html", ""),
        page.get("timestamp", ""),
        page.get("url", ""),
        limit,
        base_domain,
    )
    content.fetched = bool(page.get("fetched"))
    return content
