"""Operation-style rules (운영방식 축) over archived snapshots.

The rules judge *how a site was operated*, never *what industry it was in* or
*what the words mean* — meaning judgments (업종·상표·오염) belong to the AI
reading. Everything here is structural counting: hidden markup, link volume,
word-frequency stuffing, near-identical bodies, language charset flow.
"""

from __future__ import annotations

import re

from ..models import CheckState, CheckStatus, RuleFindings
from .extract import SnapshotContent

# 짧은 항목을 쉼표·막대기호로 8번 넘게 이어 붙인 구간 = 키워드 나열.
_KEYWORD_LIST = re.compile(r"(?:[^,|·\n]{1,20}[,|·]\s*){8,}")
_DOORWAY_PHRASES = ("지역별", "전국", "추천 순위", "best price", "cheap", "for sale online")

LINK_FARM_LINKS = 50
LINK_FARM_HOSTS = 20
DUPLICATE_SIMILARITY = 0.9


def analyze(snapshots: list[SnapshotContent]) -> RuleFindings:
    """Run every operation-style rule over the collected snapshots."""
    findings = RuleFindings()
    usable = [s for s in snapshots if s.fetched and (s.text or s.link_texts)]
    if not usable:
        findings.check = CheckState(
            status=CheckStatus.UNCHECKED, note="본문을 가져온 스냅샷이 없어 규칙 검사를 못 했습니다."
        )
        return findings

    real = [s for s in usable if not s.parking]
    findings.parking_ratio = round(1 - len(real) / len(usable), 3)
    if findings.parking_ratio >= 0.5:
        findings.evidence.append(f"수집한 스냅샷의 {int(findings.parking_ratio * 100)}%가 파킹 페이지였습니다.")

    # 숨김 텍스트·링크
    hidden = [s for s in usable if s.hidden_marks]
    if hidden:
        findings.hidden_text = True
        findings.risk_timestamps.append(hidden[0].timestamp)
        findings.evidence.append(
            f"{hidden[0].timestamp[:4]}년 페이지에 숨긴 글자·링크 흔적: {hidden[0].hidden_marks[0]}"
        )

    # 외부 링크 무더기
    for snap in real:
        if snap.external_links >= LINK_FARM_LINKS and snap.external_hosts >= LINK_FARM_HOSTS:
            findings.link_farm = True
            findings.risk_timestamps.append(snap.timestamp)
            findings.evidence.append(
                f"{snap.timestamp[:4]}년 페이지에 외부 사이트 링크 {snap.external_links}개"
                f"(서로 다른 사이트 {snap.external_hosts}곳)가 깔려 있습니다."
            )
            break

    # 도어웨이 흔적 — 키워드 나열 + 앵커 반복
    for snap in real:
        reason = doorway_reason(snap)
        if reason:
            findings.doorway = True
            findings.risk_timestamps.append(snap.timestamp)
            findings.evidence.append(f"{snap.timestamp[:4]}년 페이지: {reason}")
            break

    # 자동생성 반복 — 연도가 다른데 본문이 사실상 같음
    duplicate = duplicate_pair(real)
    if duplicate:
        findings.autogenerated = True
        findings.evidence.append(
            f"{duplicate[0]}년과 {duplicate[1]}년 페이지 본문이 거의 같습니다(자동 생성 의심)."
        )

    # 언어 흐름
    langs = [s.lang for s in real if s.lang != "unknown"]
    findings.languages = sorted(set(langs))
    findings.language_shift = len(set(langs)) > 1 and bool(langs) and langs[0] != langs[-1]

    findings.check = CheckState(status=CheckStatus.OK)
    return findings


def doorway_reason(snap: SnapshotContent) -> str:
    """Keyword-stuffed listing pages built to funnel search traffic."""
    text = snap.text
    if not text:
        return ""
    if _KEYWORD_LIST.search(text):
        return "키워드를 쉼표로 길게 나열한 구간이 있습니다."
    words = re.findall(r"[가-힣A-Za-z]{2,}", text.lower())
    # 한 낱말이 본문의 15%를 넘게 차지하면 사람이 읽으라고 쓴 글이 아니다.
    if len(words) >= 150:
        top, count = _most_common(words)
        if count / len(words) > 0.15:
            return f"'{top}' 낱말이 본문의 {int(count / len(words) * 100)}%를 차지합니다(키워드 채우기)."
    if len(snap.link_texts) >= 40:
        unique = len({t.lower() for t in snap.link_texts})
        if unique <= len(snap.link_texts) * 0.4:
            return f"거의 같은 링크 글귀 {len(snap.link_texts)}개가 반복됩니다."
        if any(phrase in text.lower() for phrase in _DOORWAY_PHRASES):
            return "지역·순위 키워드를 붙인 유사 페이지 링크가 대량으로 있습니다."
    return ""


def duplicate_pair(snapshots: list[SnapshotContent]) -> tuple[int, int] | None:
    """Two snapshots from different years whose text is near-identical."""
    scored = [(s, _shingles(s.text)) for s in snapshots if len(s.text) >= 300]
    for i in range(len(scored)):
        for j in range(i + 1, len(scored)):
            left, right = scored[i], scored[j]
            if left[0].year == right[0].year:
                continue
            if jaccard(left[1], right[1]) >= DUPLICATE_SIMILARITY:
                return left[0].year, right[0].year
    return None


def jaccard(left: set[str], right: set[str]) -> float:
    if not left or not right:
        return 0.0
    return len(left & right) / len(left | right)


def _shingles(text: str, size: int = 4) -> set[str]:
    words = re.findall(r"[가-힣A-Za-z0-9]+", text.lower())
    return {" ".join(words[i : i + size]) for i in range(max(0, len(words) - size + 1))}


def _most_common(words: list[str]) -> tuple[str, int]:
    counts: dict[str, int] = {}
    for word in words:
        counts[word] = counts.get(word, 0) + 1
    return max(counts.items(), key=lambda kv: kv[1])
