"""판정 — AI 종합 판정 + 기계 거부권.

사람이 정한 감점표(45/20/15/20점)는 폐지했다. 뜻 읽기(과거 운영이 스팸이었나,
살 가치가 있나, 어떤 주제로 이어야 하나)는 AI가 하고, 기계는 사실만으로
거부권을 행사한다:

  0. 공개 위험 명단(UT1 툴루즈) 등재 → 무조건 제외(2단에서 바로 끝난다)
  1. 전과 명단(스팸하우스·세이프 브라우징) 등재 → 무조건 제외
  2. 규칙 검사(구조 세기)가 스팸 흔적 3종 이상 → 제외
  3. AI가 인용을 들고 확신(0.7 이상)으로 스팸 판정 → 제외
  4. 필수 검사가 하나라도 미확인 → 합격 도장 금지(검토로 강등)
  5. AI 없이 돌았으면 합격 도장 없음 — 뜻 읽기 없이 ✅를 찍지 않는다

점수는 AI가 매긴 '매입 매력도'(0~100)다 — 여러 도메인 중 어떤 것을 살지
줄 세우는 비교용 잣대. 과거의 깨끗함 + 이어받을 연속성 가치를 종합한다.
"""

from __future__ import annotations

from ..models import (
    AVAILABILITY_LABEL,
    CHECK_LABEL,
    REQUIRED_CHECKS,
    VERDICT_LABEL,
    DomainResult,
    Score,
    Verdict,
)

# AI 단독 치명 판정에 필요한 확신도. 0.85에서 내림 — 돈이 걸린 매입 판단에서는
# "스팸 같은데 확신이 조금 모자라 통과"가 "멀쩡한데 잘못 막음"보다 훨씬 비싸다
# (진상 검증 지적 7, 2026-08-11). 인용(quotes) 필수는 그대로 둔다.
AI_FATAL_CONFIDENCE = 0.7
RULES_FATAL_HITS = 3  # AI 없이 규칙만으로 치명(❌)을 낼 최소 흔적 수


def _check_of(result: DomainResult, name: str):
    return {
        "blocklist": result.blocklist.check,
        "wayback": result.wayback.check,
        "registration": result.registration.check,
        "spamhaus": result.spamhaus.check,
        "index": result.index.check,
        "ai": result.ai.check,
        "rules": result.rules.check,
        "safebrowsing": result.safebrowsing.check,
    }[name]


def judge(result: DomainResult) -> DomainResult:
    """기계 거부권 → AI 종합 판정 순서로 최종 도장을 정한다(제자리 수정)."""
    result.scoring = Score()  # 수제 감점표는 폐지 — 예전 저장분과의 호환용 빈 껍데기
    ai_ok = result.ai.check.ok
    result.score = result.ai.buy_score if ai_ok else None
    result.partial_score = not ai_ok  # AI 뜻 읽기 없이 나온 결과는 참고치

    fatal = fatal_reasons(result)
    warn = warn_reasons(result)
    result.fatal_reasons = fatal
    result.warn_reasons = warn
    result.unchecked = [
        CHECK_LABEL[name]
        for name in CHECK_LABEL
        if _check_of(result, name).status.value == "UNCHECKED"
    ]
    result.not_run = [
        CHECK_LABEL[name]
        for name in CHECK_LABEL
        if _check_of(result, name).status.value == "NOT_RUN"
    ]

    required_all_ok = all(_check_of(result, name).ok for name in REQUIRED_CHECKS)
    no_history = result.wayback.check.ok and not result.wayback.has_history

    # 1. 기계 거부권(사실 기반 치명)
    if fatal:
        result.verdict = Verdict.REJECT
    # 2. AI의 제외 판정 — 치명 사유로 승격해 이유가 바로 읽히게 한다
    elif ai_ok and result.ai.verdict == "reject":
        result.verdict = Verdict.REJECT
        result.fatal_reasons = [
            result.ai.verdict_reason or "AI가 이 도메인을 매입 제외로 판정했습니다."
        ]
    # 3. 경고가 있으면 합격 도장 금지
    elif warn:
        result.verdict = Verdict.NO_HISTORY if no_history else Verdict.REVIEW
    # 4. 합격은 AI의 '사도 됨' 판정 + 필수 검사 전부 확인일 때만
    elif ai_ok and result.ai.verdict == "buy" and required_all_ok:
        result.verdict = Verdict.BUY
    # 5. AI가 유보했거나 AI 없이 돌았으면 사람 검토로 — 뜻 읽기 없이 ✅는 없다
    else:
        result.verdict = Verdict.REVIEW

    result.verdict_label = VERDICT_LABEL[result.verdict]
    if not result.one_liner:
        result.one_liner = (
            result.ai.one_liner or result.ai.verdict_reason or plain_one_liner(result)
        )
    if not result.recommended_topics:
        result.recommended_topics = result.ai.recommended_topics
    result.acquisition = result.registration.acquisition
    result.availability = availability_of(result.registration.acquisition)
    result.availability_label = AVAILABILITY_LABEL[result.availability]
    return result


def plain_one_liner(result: DomainResult) -> str:
    """AI 없이 모은 사실만으로 만드는 한 줄 평가 — 지어내지 않고 센 것만 적는다."""
    # 빨간 도장이 찍힌 도메인 옆에 안심시키는 말부터 나오면 안 된다.
    parts = [result.fatal_reasons[0]] if result.fatal_reasons else []
    history = result.wayback
    if history.check.ok and history.has_history:
        span = ""
        if history.first_seen and history.last_seen:
            span = f"{history.first_seen[:4]}~{history.last_seen[:4]}년 "
        parts.append(f"{span}저장된 화면 {history.total_captures}장이 남아 있음")
    elif history.check.ok:
        parts.append("저장된 과거 화면이 아예 없음")

    if result.rules.check.ok:
        marks = [
            name
            for name, hit in (
                ("도어웨이", result.rules.doorway),
                ("숨긴 글자", result.rules.hidden_text),
                ("링크 무더기", result.rules.link_farm),
                ("자동 생성 반복", result.rules.autogenerated),
            )
            if hit
        ]
        if marks:
            parts.append("규칙 검사가 잡은 흔적: " + ", ".join(marks))
        else:
            parts.append("규칙 검사에서 나쁜 운영 흔적은 안 나옴")
        if result.rules.parking_ratio >= 0.3:
            parts.append(f"과거 화면의 {int(result.rules.parking_ratio * 100)}%가 판매용 빈 화면이었음")

    if result.index.check.ok:
        if result.index.current_parking:
            parts.append("지금은 판매용 빈 화면임")
        else:
            parts.append(f"지금 웹에 남은 페이지 {result.index.indexed_count}건")

    return ". ".join(parts) + "." if parts else "판단할 자료를 거의 모으지 못했습니다."


def availability_of(acquisition: str) -> str:
    """Fold the acquisition status into one buy-now axis for the UI column."""
    if "미등록" in acquisition:
        return "free"
    if "삭제 대기" in acquisition:
        return "soon"
    if "복원" in acquisition:
        return "auction"
    # "등록 제한" = 예약어(기관 전용) — 주인은 없지만 일반인은 살 수 없다.
    if "등록 중" in acquisition or "자동 갱신" in acquisition or "등록 제한" in acquisition:
        return "taken"
    return "unknown"


def fatal_reasons(result: DomainResult) -> list[str]:
    """기계 거부권 — 명단 등재, 또는 확정된 스팸 운영."""
    reasons = []
    if result.blocklist.check.ok and result.blocklist.listed:
        reasons.append("세계 공개 위험 명단에 올라 있습니다: " + ", ".join(result.blocklist.codes))
    if result.spamhaus.check.ok and result.spamhaus.listed:
        reasons.append("스팸하우스 블랙리스트에 올라 있습니다: " + ", ".join(result.spamhaus.codes))
    if result.safebrowsing.check.ok and result.safebrowsing.listed:
        reasons.append("구글 세이프 브라우징에 위험으로 등재되어 있습니다: " + ", ".join(result.safebrowsing.codes))

    spam = result.ai.spam
    ai_says_spam = result.ai.check.ok and spam.verdict == "spam"
    rules_say_spam = result.rules.check.ok and result.rules.spam_operation
    rule_hits = sum(
        [
            result.rules.doorway,
            result.rules.hidden_text,
            result.rules.link_farm,
            result.rules.autogenerated,
        ]
    )
    if ai_says_spam and rules_say_spam:
        reasons.append("규칙 검사와 AI가 모두 스팸 운영으로 판정했습니다.")
    # 기계적 흔적이 세 종류 넘게 겹치면 그 자체로 충분한 근거다. AI를 켰는지와
    # 무관하게 적용한다 — AI를 켜면 ❌가 ⚠️로 물러지는 거꾸로 된 유인을 막기 위해서다.
    elif result.rules.check.ok and rule_hits >= RULES_FATAL_HITS:
        reasons.append(
            f"규칙 검사가 스팸 운영 흔적을 {rule_hits}종 찾았습니다(기계적 검사만으로도 확정)."
        )
    elif ai_says_spam and spam.confidence >= AI_FATAL_CONFIDENCE and spam.quotes:
        reasons.append(
            f"AI가 확신도 {spam.confidence:.2f}로 스팸 운영이라고 판정했습니다(근거 인용: "
            f"“{spam.quotes[0][:80]}”)."
        )
    return reasons


def warn_reasons(result: DomainResult) -> list[str]:
    """치명은 아니지만 ✅를 막아야 하는 것들."""
    reasons = []
    # 과거가 아예 없는 도메인은 "이력 없음" 한 줄로 충분하다. 규칙 검사 미확인까지
    # 함께 적으면 같은 사실을 두 번 말하는 데다, 고칠 수 있는 실패처럼 읽힌다.
    no_history = result.wayback.check.ok and not result.wayback.has_history
    for name in REQUIRED_CHECKS:
        if name == "rules" and no_history:
            continue
        check = _check_of(result, name)
        if not check.ok:
            reasons.append(f"필수 검사 미확인 — {CHECK_LABEL[name]}: {check.note or '확인하지 못했습니다.'}")

    spam = result.ai.spam
    ai_says_spam = result.ai.check.ok and spam.verdict == "spam"
    rules_say_spam = result.rules.check.ok and result.rules.spam_operation
    # 규칙이 스팸 흔적을 찾았는데 AI가 스팸이라 답하지 않은 경우는 전부 충돌이다
    # (clean·unclear·unknown 모두) — 유보를 무혐의로 읽어 ✅를 내주던 구멍을 막는다.
    # AI를 안 돌린 경우(키 없음·실패)에도 규칙이 잡은 흔적은 그대로 경고로 남긴다.
    # 이 줄이 없으면 규칙이 도어웨이·숨긴 글자를 찾아 놓고도 아무 말 없이 ✅가 나간다.
    if rules_say_spam and not result.ai.check.ok:
        reasons.append(
            "규칙 검사가 스팸 운영 흔적을 찾았습니다(AI 확인 없이 기계적 검사만으로 본 결과입니다)."
        )
    elif rules_say_spam and result.ai.check.ok and spam.verdict != "spam":
        reasons.append(
            "신호 충돌 — 규칙 검사는 스팸 흔적을 찾았는데 AI는 스팸이라고 보지 않았습니다"
            f"(AI 판정: {spam.verdict})."
        )
    elif ai_says_spam and not rules_say_spam:
        reasons.append("신호 충돌 — AI는 스팸으로 봤지만 규칙 검사에서는 흔적을 찾지 못했습니다.")

    if result.ai.check.ok and result.ai.trademark_risk:
        reasons.append("상표 충돌 의심 — AI 소견: " + (result.ai.trademark or "상표 문제 가능성 있음"))
    if result.wayback.excluded:
        reasons.append("웨이백 열람이 차단되어 과거를 볼 수 없습니다(이력 은폐 가능성).")
    # 기록 공백이 길면 그 기간은 아무도 못 본 것이다 — 전수 확인을 해도
    # 보관소에 없는 세월은 못 본다는 사실을 노랑으로 정직하게 남긴다(진상 지적 9).
    if result.wayback.check.ok and len(result.wayback.gap_years) >= 2:
        reasons.append(
            f"저장 기록이 없는 해가 {len(result.wayback.gap_years)}년 있습니다 — "
            "그 기간의 운영 내용은 아무 자료로도 확인할 수 없습니다."
        )
    if result.wayback.check.ok and not result.wayback.has_history:
        reasons.append("저장된 과거 이력이 아예 없습니다 — 좋은 것도 나쁜 것도 아니므로 신중히 판단하세요.")
    return reasons
