"""Score and verdict — PLAN §2 implemented literally.

Points: 45 안전성 / 20 이력 건실성 / 15 전환 방향 / 20 승계 자산.
An unconfirmed item is neither 0 nor full marks: it leaves the denominator and
the rest is normalised into a 부분 점수(참고치).

Verdict priority (first matching rule wins):
  1. 치명 → ❌   2. 점수<50 → ❌ (필수 전부 확인 + 점수 산출 가능할 때만)
  3. ⚠️ 강제     4. 구간 (75+ ✅ / 50~74 ⚠️)
"""

from __future__ import annotations

from ..models import (
    AVAILABILITY_LABEL,
    CHECK_LABEL,
    REQUIRED_CHECKS,
    VERDICT_LABEL,
    DomainResult,
    Score,
    ScoreItem,
    Verdict,
)

BUY_CUT = 75.0
REJECT_CUT = 50.0
AI_FATAL_CONFIDENCE = 0.85  # AI 단독 치명 판정에 필요한 확신도


def _check_of(result: DomainResult, name: str):
    return {
        "wayback": result.wayback.check,
        "registration": result.registration.check,
        "spamhaus": result.spamhaus.check,
        "index": result.index.check,
        "ai": result.ai.check,
        "authority": result.authority.check,
        "safebrowsing": result.safebrowsing.check,
        "virustotal": result.virustotal.check,
    }[name]


def compute_score(result: DomainResult) -> Score:
    """Four scored items; each one is dropped from the denominator if unconfirmed."""
    items = [
        _safety_item(result),
        _history_item(result),
        _transition_item(result),
        _inheritance_item(result),
    ]
    score = Score(items=items)
    counted = [i for i in items if i.earned is not None]
    denominator = sum(i.max_points for i in counted)
    score.partial = len(counted) != len(items)
    score.computable = bool(counted) and denominator > 0
    if score.computable:
        score.total = round(sum(i.earned for i in counted) / denominator * 100, 1)
    return score


def _safety_item(result: DomainResult) -> ScoreItem:
    item = ScoreItem(name="safety", label="과거 콘텐츠 안전성", max_points=45)
    ai_ok = result.ai.check.ok
    rules_ok = result.rules.check.ok
    if not (ai_ok or rules_ok):
        item.note = "과거 본문을 읽지 못해 채점에서 제외했습니다."
        return item

    points = 45.0
    notes = []
    if ai_ok:
        spam = result.ai.spam
        if spam.verdict == "spam":
            points -= 45 * max(0.3, spam.confidence)
            notes.append(f"AI가 스팸 운영으로 봄(확신도 {spam.confidence:.2f})")
        elif spam.verdict == "unclear":
            points -= 45 * 0.3 * max(0.3, spam.confidence)
            notes.append("AI가 판단을 유보함")
    if rules_ok:
        hits = sum(
            [
                result.rules.doorway,
                result.rules.hidden_text,
                result.rules.link_farm,
                result.rules.autogenerated,
            ]
        )
        if hits:
            points -= min(36.0, hits * 12.0)
            notes.append(f"운영방식 규칙 위반 {hits}종")
    if result.index.check.ok and result.index.contaminated:
        points -= 15.0
        notes.append("색인에 위험 문구 잔존")

    item.earned = max(0.0, min(45.0, points))
    item.note = ", ".join(notes) or "위험 신호 없음"
    return item


def _history_item(result: DomainResult) -> ScoreItem:
    item = ScoreItem(name="history", label="이력 건실성", max_points=20)
    history = result.wayback
    if not history.check.ok or not history.has_history:
        item.note = "저장된 이력이 없어 채점에서 제외했습니다."
        return item

    points = 20.0
    notes = []
    age = history.age_years
    if age < 2:
        points -= 9
        notes.append("운영 기간 2년 미만")
    elif age < 5:
        points -= 5
        notes.append("운영 기간 5년 미만")
    elif age < 10:
        points -= 2

    if history.redirect_ratio > 0.5:
        points -= 6
        notes.append("리다이렉트 남발")
    elif history.redirect_ratio > 0.3:
        points -= 3

    if result.rules.check.ok:
        if result.rules.parking_ratio >= 0.5:
            points -= 5
            notes.append("파킹 비중 높음")
        elif result.rules.parking_ratio >= 0.3:
            points -= 2

    if history.gap_years:
        # 공백 단독은 소폭. 공백 직후 주제·언어가 뒤집힌 조합만 위험으로 본다.
        if result.rules.check.ok and result.rules.language_shift:
            points -= 6
            notes.append("기록 공백 직후 주제·언어가 바뀜")
        else:
            points -= min(3.0, len(history.gap_years))
            notes.append(f"기록 공백 {len(history.gap_years)}년")

    item.earned = max(0.0, min(20.0, points))
    item.note = ", ".join(notes) or f"약 {age:.0f}년간 꾸준히 운영"
    return item


def _transition_item(result: DomainResult) -> ScoreItem:
    item = ScoreItem(name="transition", label="전환 방향", max_points=15)
    ai_ok = result.ai.check.ok
    rules_ok = result.rules.check.ok
    if not (ai_ok or rules_ok):
        item.note = "전환 흐름을 확인할 자료가 없어 채점에서 제외했습니다."
        return item

    points = 15.0
    notes = []
    if ai_ok:
        # 서술문 낱말 검색은 "위험 전환은 없었습니다"까지 감점하던 오탐원이었다.
        # 이제 AI가 스키마로 직접 답한 boolean 하나만 본다.
        if result.ai.transition_risk:
            points -= 9
            notes.append("정상→위험 방향 전환 소견")
        elif any(word in result.ai.transition for word in ("전환", "변화", "바뀌")):
            points -= 2
            notes.append("주제 전환 있음(정상 범위)")
    if rules_ok:
        if result.rules.language_shift:
            points -= 6
            notes.append("사용 언어가 도중에 바뀜")
        if result.rules.sensitive_terms:
            points -= 3
            notes.append("민감 업종 낱말 등장(주의 표지)")

    item.earned = max(0.0, min(15.0, points))
    item.note = ", ".join(notes) or "주제 흐름이 일관됨"
    return item


def _inheritance_item(result: DomainResult) -> ScoreItem:
    """가점형 — 색인 0은 만료 도메인의 기본값이므로 중립에서 시작한다."""
    item = ScoreItem(name="inheritance", label="승계 자산", max_points=20)
    authority_ok = result.authority.check.ok
    index_ok = result.index.check.ok
    if not (authority_ok or index_ok):
        item.note = "승계 자산 자료가 없어 채점에서 제외했습니다."
        return item

    points = 10.0  # 중립
    notes = []
    if authority_ok:
        bonus = min(7.0, result.authority.page_rank * 1.4)
        points += bonus
        notes.append(f"권위 점수 {result.authority.page_rank:.2f}")
    if index_ok:
        if result.index.indexed_count >= 10:
            points += 3
            notes.append(f"색인 {result.index.indexed_count}건 잔존")
        elif result.index.indexed_count >= 1:
            points += 1.5
            notes.append(f"색인 {result.index.indexed_count}건 잔존")
        else:
            notes.append("색인 없음(중립)")

    item.earned = max(0.0, min(20.0, points))
    item.note = ", ".join(notes)
    return item


def judge(result: DomainResult) -> DomainResult:
    """Fill score, verdict and the reason lists on the result (in place)."""
    result.scoring = compute_score(result)
    result.score = result.scoring.total
    result.partial_score = result.scoring.partial

    fatal = fatal_reasons(result)
    warn = warn_reasons(result)
    result.fatal_reasons = fatal
    result.warn_reasons = warn
    result.unchecked = [
        CHECK_LABEL[name]
        for name in CHECK_LABEL
        if _check_of(result, name).status.value == "UNCHECKED"
    ]
    result.not_run = [
        CHECK_LABEL[name]
        for name in CHECK_LABEL
        if _check_of(result, name).status.value == "NOT_RUN"
    ]

    # 1. 치명
    if fatal:
        result.verdict = Verdict.REJECT
    else:
        required_all_ok = all(_check_of(result, name).ok for name in REQUIRED_CHECKS)
        # 2. 점수 미달 — 필수 검사가 전부 확인되고 점수를 낼 수 있을 때만
        if (
            required_all_ok
            and result.scoring.computable
            and result.score is not None
            and result.score < REJECT_CUT
        ):
            result.verdict = Verdict.REJECT
            result.fatal_reasons = [f"점수 {result.score:.0f}점으로 기준(50점) 미만입니다."]
        # 3. ⚠️ 강제
        elif warn:
            no_history = result.wayback.check.ok and not result.wayback.has_history
            result.verdict = Verdict.NO_HISTORY if no_history else Verdict.REVIEW
        # 4. 구간
        elif result.score is not None and result.score >= BUY_CUT:
            result.verdict = Verdict.BUY
        else:
            result.verdict = Verdict.REVIEW

    result.verdict_label = VERDICT_LABEL[result.verdict]
    if not result.one_liner:
        result.one_liner = result.ai.one_liner
    if not result.recommended_topics:
        result.recommended_topics = result.ai.recommended_topics
    result.acquisition = result.registration.acquisition
    result.availability = availability_of(result.registration.acquisition)
    result.availability_label = AVAILABILITY_LABEL[result.availability]
    return result


def availability_of(acquisition: str) -> str:
    """Fold the acquisition status into one buy-now axis for the UI column."""
    if "미등록" in acquisition:
        return "free"
    if "삭제 대기" in acquisition:
        return "soon"
    if "복원" in acquisition:
        return "auction"
    if "등록 중" in acquisition or "자동 갱신" in acquisition:
        return "taken"
    return "unknown"


def fatal_reasons(result: DomainResult) -> list[str]:
    """Rule 1 — institutional listing, confirmed spam operation, index contamination."""
    reasons = []
    if result.spamhaus.check.ok and result.spamhaus.listed:
        reasons.append("스팸하우스 블랙리스트에 올라 있습니다: " + ", ".join(result.spamhaus.codes))
    if result.safebrowsing.check.ok and result.safebrowsing.listed:
        reasons.append("구글 세이프 브라우징에 위험으로 등재되어 있습니다: " + ", ".join(result.safebrowsing.codes))

    spam = result.ai.spam
    ai_says_spam = result.ai.check.ok and spam.verdict == "spam"
    rules_say_spam = result.rules.check.ok and result.rules.spam_operation
    if ai_says_spam and rules_say_spam:
        reasons.append("규칙 검사와 AI가 모두 스팸 운영으로 판정했습니다.")
    elif ai_says_spam and spam.confidence >= AI_FATAL_CONFIDENCE and spam.quotes:
        reasons.append(
            f"AI가 확신도 {spam.confidence:.2f}로 스팸 운영이라고 판정했습니다(근거 인용: "
            f"“{spam.quotes[0][:80]}”)."
        )
    if result.index.check.ok and result.index.contaminated:
        reasons.append("현재 구글 색인에 위험 업종 문구가 남아 있습니다: " + ", ".join(result.index.contamination_terms[:5]))
    return reasons


def warn_reasons(result: DomainResult) -> list[str]:
    """Rule 3 — anything that forbids a ✅ even when nothing fatal was found."""
    reasons = []
    for name in REQUIRED_CHECKS:
        check = _check_of(result, name)
        if not check.ok:
            reasons.append(f"필수 검사 미확인 — {CHECK_LABEL[name]}: {check.note or '확인하지 못했습니다.'}")

    spam = result.ai.spam
    ai_says_spam = result.ai.check.ok and spam.verdict == "spam"
    rules_say_spam = result.rules.check.ok and result.rules.spam_operation
    # 규칙이 스팸 흔적을 찾았는데 AI가 스팸이라 답하지 않은 경우는 전부 충돌이다
    # (clean·unclear·unknown 모두) — 유보를 무혐의로 읽어 ✅를 내주던 구멍을 막는다.
    if rules_say_spam and result.ai.check.ok and spam.verdict != "spam":
        reasons.append(
            "신호 충돌 — 규칙 검사는 스팸 흔적을 찾았는데 AI는 스팸이라고 보지 않았습니다"
            f"(AI 판정: {spam.verdict})."
        )
    elif ai_says_spam and not rules_say_spam:
        reasons.append("신호 충돌 — AI는 스팸으로 봤지만 규칙 검사에서는 흔적을 찾지 못했습니다.")

    if result.rules.brand_hits:
        reasons.append("상표 충돌 의심 — 도메인 이름에 " + ", ".join(result.rules.brand_hits) + " 가 들어 있습니다.")
    if result.ai.check.ok and result.ai.trademark_risk:
        reasons.append("상표 충돌 의심 — AI 소견: " + (result.ai.trademark or "상표 문제 가능성 있음"))
    if result.rules.sensitive_terms:
        reasons.append(
            "민감 업종 이력(합법일 수 있음, 사람이 확인 필요): "
            + ", ".join(result.rules.sensitive_terms[:5])
        )
    if result.wayback.excluded:
        reasons.append("웨이백 열람이 차단되어 과거를 볼 수 없습니다(이력 은폐 가능성).")
    if result.wayback.check.ok and not result.wayback.has_history:
        reasons.append("저장된 과거 이력이 아예 없습니다 — 좋은 것도 나쁜 것도 아니므로 신중히 판단하세요.")
    if result.virustotal.check.ok and (result.virustotal.malicious or result.virustotal.suspicious):
        reasons.append(
            f"바이러스토탈 악성 {result.virustotal.malicious}건·의심 {result.virustotal.suspicious}건."
        )
    return reasons
